<h1 style="margin-top:15px">Ensembl Core - Schema documentation</h1>


<p>
This document gives a high-level description of the tables that
make up the EnsEMBL core schema. Tables are grouped into logical
groups, and the purpose of each table is explained. It is intended to
allow people to familiarise themselves with the schema when
encountering it for the first time, or when they need to use some
tables that they've not used before.
</p>

<p>
This document refers to version <span style="font-weight:bold;font-size:11pt;color:#000">####DB_VERSION####</span> of the EnsEMBL
core schema.
</p>

<p>
The overall diagram can be found <a target="_blank" href="./diagrams/Core.svg">here</a>.
</p>
