<p>
<a href="http://www.ebi.ac.uk"><img src="/img/ebi_logo.png" alt="EMBL-EBI" title="European BioInformatics Institute" style="width:100px;height:31px" class="float-left ebi-logo" /></a>
<a href="https://www.elixir-europe.org/platforms/data/core-data-resources"><img src="/img/Elixir_CDR-mini.png" alt="Elixir logo" style="width:100px;height:73px" class="float-right"/></a>
<a href="https://globalbiodata.org/scientific-activities/global-core-biodata-resources"><img src="/img/GCBR-Logo-RGB.svg" alt="Global Bio Data logo" style="width:100px;height:73px" class="float-right"/></a>
  Ensembl creates, integrates and distributes reference datasets and analysis tools that enable genomics. We are based at <a href="http://www.ebi.ac.uk/" rel="external">EMBL-EBI</a> and our software and data are freely available.</p>
<p>Our <a href="/info/about/credits.html">acknowledgements page</a> includes a list of current and previous funding bodies. <a href="/info/about/publications.html">How to cite Ensembl</a> in your own publications.</p>

