<p><a href="http://www.sanger.ac.uk"><img src="/img/wtsi_rev.png" alt="WTSI" title="Wellcome Trust Sanger Institute" style="width:98px;height:30px" class="float-left" /></a>
      <a href="http://www.ebi.ac.uk"><img src="/img/ebi_logo.png" alt="EMBL-EBI" title="European BioInformatics Institute" style="width:100px;height:31px" class="float-right" /></a>
      Ensembl is a joint project between <a href="http://www.ebi.ac.uk/">EMBL&nbsp;-&nbsp;EBI</a> and the <a href="http://www.sanger.ac.uk/">Wellcome&nbsp;Trust&nbsp;Sanger&nbsp;Institute</a>  to develop a software system which produces and maintains automatic annotation on selected eukaryotic genomes.</p>
<p>Ensembl receives major funding from the Wellcome Trust.
Our <a href="/info/about/credits.html">acknowledgements page</a> includes a list of additional current and previous funding bodies.</p>

