<h2 class="first">New to Ensembl?</h2>

<p>
Did you know you can:
</p>

<dl>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/info/website/help/control_panel.html#cp-panel">Add custom tracks</a></dt>
<dd>using our new Control Panel</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/info/website/help/control_panel.html#cp-data">Upload your own data</a></dt>
<dd>and save it to your Ensembl account</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/Multi/blastview">Search for a DNA or protein sequence</a></dt>
<dd>using BLAST or BLAT</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/info/data/api.html">Fetch only the data you want</a></dt>
<dd>from our public database, using the Ensembl Perl API</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/info/data/ftp/">Download our databases via FTP</a></dt>
<dd>in FASTA, MySQL and other formats</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/biomart/martview">Mine Ensembl with BioMart</a></dt>
<dd>and export sequences or tables in text, html, or Excel format</dd>
</dl>

<p>Still got questions? <a href="/Help/Faq" class="modal_link">Try our FAQs</a></p>
