<h2 class="first">New to Ensembl?</h2>

<div class="info-box" style="float:right;width:50%;padding:10px;margin:5px">
<img src="/i/new_star.gif" style="float:left;padding-right:5px" alt="NEW!" />
<strong>The new Ensembl website</strong><br />
We've made some changes to our site, to make it faster and easier to use.
<br /><a href="/info/docs/webcode/version_4.html">Find out more about what we've changed and why</a>!
</div>

<p>
Did you know you can:
</p>

<dl>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/info/website/help/control_panel.html#cp-panel">Add custom tracks</a></dt>
<dd>using our new Control Panel</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/info/website/help/control_panel.html#cp-data">Upload your own data</a></dt>
<dd>and save it to your Ensembl account</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/Multi/blastview">Search for a DNA or protein sequence</a></dt>
<dd>using BLAST or BLAT</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/info/data/api/">Fetch only the data you want</a></dt>
<dd>from our public database, using the Ensembl Perl API</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/info/data/ftp/">Download our databases via FTP</a></dt>
<dd>in FASTA, MySQL and other formats</dd>
<dt><img src="/i/e-quest.gif" style="width:20px;height:19px;vertical-align:middle;padding-right:4px" alt="(e?)" />
<a href="/biomart/martview">Mine Ensembl with BioMart</a></dt>
<dd>and export sequences or tables in text, html, or Excel format</dd>
</dl>

<p>Still got questions? <a href="/Help/Faq" class="modal_link">Try our FAQs</a></p>
