
<table class="ss" cellpadding="4">

<tr>
<th>Species</th>
<th>DNA</th>
<th>cDNA</th>
<th>Peptides</th>
<th>EMBL</th>
<th>GenBank</th>
<th>MySQL</th>
<th>GTF</th>
<th>EMF</th>
</tr>


<tr>
<td><strong><i>Aedes aegypti</i></strong> (yellow fever mosquito)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/aedes_aegypti/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/aedes_aegypti/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Anopheles gambiae</i></strong> (African malaria mosquito)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/anopheles_gambiae/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/anopheles_gambiae/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Bos taurus</i></strong> (cattle)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/bos_taurus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/bos_taurus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Caenorhabditis elegans</i></strong> (nematode)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/caenorhabditis_elegans/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/caenorhabditis_elegans/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Canis familiaris</i></strong> (dog)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/canis_familiaris/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/canis_familiaris/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Cavia porcellus</i></strong> (domestic guinea pig)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/cavia_porcellus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/cavia_porcellus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ciona intestinalis</i></strong> (Sea squirt Ciona intestinalis)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/ciona_intestinalis/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/ciona_intestinalis/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ciona savignyi</i></strong> (Sea squirt Ciona savignyi)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/ciona_savignyi/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/ciona_savignyi/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Danio rerio</i></strong> (zebrafish)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/danio_rerio/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/danio_rerio/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Dasypus novemcinctus</i></strong> (nine-banded armadillo)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/dasypus_novemcinctus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/dasypus_novemcinctus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Drosophila melanogaster</i></strong> (fruit fly)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/drosophila_melanogaster/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/drosophila_melanogaster/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Echinops telfairi</i></strong> (small Madagascar hedgehog)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/echinops_telfairi/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/echinops_telfairi/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Equus caballus</i></strong> (horse)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/equus_caballus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/equus_caballus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/equus_caballus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/equus_caballus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/equus_caballus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Erinaceus europaeus</i></strong> (western European hedgehog)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/erinaceus_europaeus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/erinaceus_europaeus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Felis catus</i></strong> (cat)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/felis_catus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/felis_catus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Gallus gallus</i></strong> (chicken)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/gallus_gallus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/gallus_gallus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Gasterosteus aculeatus</i></strong> (three spined stickleback)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/gasterosteus_aculeatus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/gasterosteus_aculeatus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Homo sapiens</i></strong> (human)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/homo_sapiens/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/homo_sapiens/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_emf/homo_sapiens/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Loxodonta africana</i></strong> (African savanna elephant)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/loxodonta_africana/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/loxodonta_africana/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Macaca mulatta</i></strong> (rhesus monkey)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/macaca_mulatta/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/macaca_mulatta/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Microcebus murinus</i></strong> (grey mouse lemur)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/microcebus_murinus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/microcebus_murinus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/microcebus_murinus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/microcebus_murinus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/microcebus_murinus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Monodelphis domestica</i></strong> (gray short-tailed opossum)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/monodelphis_domestica/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/monodelphis_domestica/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Mus musculus</i></strong> (house mouse)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/mus_musculus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/mus_musculus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_emf/mus_musculus/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Myotis lucifugus</i></strong> (little brown bat)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/myotis_lucifugus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/myotis_lucifugus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ochotona princeps</i></strong> (American pika)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ochotona_princeps/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ochotona_princeps/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ochotona_princeps/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/ochotona_princeps/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/ochotona_princeps/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ornithorhynchus anatinus</i></strong> (platypus)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/ornithorhynchus_anatinus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/ornithorhynchus_anatinus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Oryctolagus cuniculus</i></strong> (rabbit)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/oryctolagus_cuniculus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/oryctolagus_cuniculus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Oryzias latipes</i></strong> (Japanese medaka)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/oryzias_latipes/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/oryzias_latipes/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Otolemur garnettii</i></strong> (small-eared galago)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/otolemur_garnettii/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/otolemur_garnettii/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Pan troglodytes</i></strong> (chimpanzee)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/pan_troglodytes/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/pan_troglodytes/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Pongo pygmaeus</i></strong> (orangutan)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/pongo_pygmaeus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/pongo_pygmaeus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/pongo_pygmaeus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/pongo_pygmaeus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/pongo_pygmaeus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Rattus norvegicus</i></strong> (Norway rat)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/rattus_norvegicus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/rattus_norvegicus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_emf/rattus_norvegicus/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Saccharomyces cerevisiae</i></strong> (baker's yeast)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/saccharomyces_cerevisiae/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/saccharomyces_cerevisiae/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Sorex araneus</i></strong> (European shrew)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/sorex_araneus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/sorex_araneus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Spermophilus tridecemlineatus</i></strong> (thirteen-lined ground squirrel)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/spermophilus_tridecemlineatus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/spermophilus_tridecemlineatus/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Takifugu rubripes</i></strong> (torafugu)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/takifugu_rubripes/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/takifugu_rubripes/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Tetraodon nigroviridis</i></strong> (Fresh water pufferfish)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/tetraodon_nigroviridis/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/tetraodon_nigroviridis/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Tupaia belangeri</i></strong> (northern tree shrew)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/tupaia_belangeri/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/tupaia_belangeri/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Xenopus tropicalis</i></strong> (western clawed frog)</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis/dna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis/cdna/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis/pep/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_embl/xenopus_tropicalis/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_genbank/xenopus_tropicalis/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong>Multi-species</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td>-</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_emf/">FTP</a></td>
</tr>
<tr>
<td><strong>Ensembl Mart</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td><a href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td>-</td>
<td>-</td>
</tr>
      </table>
