// Generated by CoffeeScript 1.12.7
(function() {
  var TextProc2;

  TextProc2 = (function() {
    function TextProc2() {
      this.candidates = {};
      this.values = {};
      this.running = [];
    }

    TextProc2.prototype.candidate = function(key, value, priority) {
      var ref, ref1;
      if (priority == null) {
        priority = (ref = (ref1 = this.candidates[key]) != null ? ref1.priority : void 0) != null ? ref : 0;
      }
      if (value == null) {
        return;
      }
      if ((this.candidates[key] == null) || this.candidates[key].priority < priority) {
        return this.candidates[key] = {
          value: value,
          priority: priority
        };
      }
    };

    TextProc2.prototype.best = function(key) {
      var ref;
      return (ref = this.candidates[key]) != null ? ref.value : void 0;
    };

    TextProc2.prototype.add_value = function(key, value, position) {
      if (!this.values[key]) {
        this.values[key] = [];
      }
      return this.values[key].push({
        value: value,
        position: position
      });
    };

    TextProc2.prototype.all_values = function(key) {
      return this.values[key];
    };

    TextProc2.prototype.send = function(key, value) {
      return this.output[key] = value;
    };

    TextProc2.prototype.register = function(prio, method) {
      return this.running.push({
        prio: prio,
        method: method
      });
    };

    TextProc2.prototype._sort_running = function() {
      var r;
      return (function() {
        var i, len, ref, results;
        ref = this.running.sort(function(a, b) {
          return a.prio - b.prio;
        });
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          r = ref[i];
          results.push(r.method);
        }
        return results;
      }).call(this);
    };

    TextProc2.prototype.run = function(data) {
      var i, k, len, r, ref, v;
      this.candidates = {};
      this.values = {};
      this.output = {};
      for (k in data) {
        v = data[k];
        this.candidate(k, v, 0);
      }
      ref = this._sort_running();
      for (i = 0, len = ref.length; i < len; i++) {
        r = ref[i];
        r.call(this);
      }
      return this.output;
    };

    return TextProc2;

  })();

  window.TextProc2 = TextProc2;

}).call(this);
