<h4>Human (Homo sapiens)</h4>
<a href="mlss/mlss_560.html">Gorilla (Gorilla gorilla)</a><br/>
<a href="mlss/mlss_559.html">Chimpanzee (Pan troglodytes)</a><br/>
<a href="mlss/mlss_557.html">Orangutan (Pongo abelii)</a><br/>
<a href="mlss/mlss_561.html">Gibbon (Nomascus leucogenys)</a><br/>
<a href="mlss/mlss_558.html">Macaque (Macaca mulatta)</a><br/>
<a href="mlss/mlss_562.html">Marmoset (Callithrix jacchus)</a><br/>
<a href="mlss/mlss_412.html">Tarsier (Tarsius syrichta)</a><br/>
<a href="mlss/mlss_429.html">Mouse Lemur (Microcebus murinus)</a><br/>
<a href="mlss/mlss_545.html">Bushbaby (Otolemur garnettii)</a><br/>
<a href="mlss/mlss_410.html">Mouse (Mus musculus)</a><br/>
<a href="mlss/mlss_393.html">Rat (Rattus norvegicus)</a><br/>
<a href="mlss/mlss_397.html">Kangaroo rat (Dipodomys ordii)</a><br/>
<a href="mlss/mlss_383.html">Squirrel (Spermophilus tridecemlineatus)</a><br/>
<a href="mlss/mlss_391.html">Guinea Pig (Cavia porcellus)</a><br/>
<a href="mlss/mlss_408.html">Pika (Ochotona princeps)</a><br/>
<a href="mlss/mlss_478.html">Rabbit (Oryctolagus cuniculus)</a><br/>
<a href="mlss/mlss_402.html">Tree Shrew (Tupaia belangeri)</a><br/>
<a href="mlss/mlss_401.html">Sloth (Choloepus hoffmanni)</a><br/>
<a href="mlss/mlss_406.html">Armadillo (Dasypus novemcinctus)</a><br/>
<a href="mlss/mlss_400.html">Lesser hedgehog tenrec (Echinops telfairi)</a><br/>
<a href="mlss/mlss_447.html">Elephant (Loxodonta africana)</a><br/>
<a href="mlss/mlss_389.html">Hyrax (Procavia capensis)</a><br/>
<a href="mlss/mlss_395.html">Hedgehog (Erinaceus europaeus)</a><br/>
<a href="mlss/mlss_382.html">Shrew (Sorex araneus)</a><br/>
<a href="mlss/mlss_521.html">Microbat (Myotis lucifugus)</a><br/>
<a href="mlss/mlss_403.html">Megabat (Pteropus vampyrus)</a><br/>
<a href="mlss/mlss_405.html">Horse (Equus caballus)</a><br/>
<a href="mlss/mlss_409.html">Cat (Felis catus)</a><br/>
<a href="mlss/mlss_404.html">Dog (Canis familiaris)</a><br/>
<a href="mlss/mlss_483.html">Panda (Ailuropoda melanoleuca)</a><br/>
<a href="mlss/mlss_396.html">Dolphin (Tursiops truncatus)</a><br/>
<a href="mlss/mlss_433.html">Pig (Sus scrofa)</a><br/>
<a href="mlss/mlss_534.html">Cow (Bos taurus)</a><br/>
<a href="mlss/mlss_407.html">Alpaca (Vicugna pacos)</a><br/>
<a href="mlss/mlss_535.html">Tasmanian devil (Sarcophilus harrisii)</a><br/>
<a href="mlss/mlss_430.html">Wallaby (Macropus eugenii)</a><br/>
<a href="mlss/mlss_385.html">Opossum (Monodelphis domestica)</a><br/>
<a href="mlss/mlss_384.html">Platypus (Ornithorhynchus anatinus)</a><br/>
<a href="mlss/mlss_390.html">Chicken (Gallus gallus)</a><br/>
<h4>Mouse (Mus musculus)</h4>
<a href="mlss/mlss_282.html">Rat (Rattus norvegicus)</a><br/>
<a href="mlss/mlss_283.html">Dog (Canis familiaris)</a><br/>
<a href="mlss/mlss_284.html">Platypus (Ornithorhynchus anatinus)</a><br/>
<a href="mlss/mlss_370.html">Medaka (Oryzias latipes)</a><br/>
<h4>Dog (Canis familiaris)</h4>
<a href="mlss/mlss_502.html">Horse (Equus caballus)</a><br/>
<a href="mlss/mlss_482.html">Panda (Ailuropoda melanoleuca)</a><br/>
<h4>Pig (Sus scrofa)</h4>
<a href="mlss/mlss_533.html">Cow (Bos taurus)</a><br/>
<h4>Opossum (Monodelphis domestica)</h4>
<a href="mlss/mlss_544.html">Tasmanian devil (Sarcophilus harrisii)</a><br/>
<a href="mlss/mlss_443.html">Wallaby (Macropus eugenii)</a><br/>
<h4>Chicken (Gallus gallus)</h4>
<a href="mlss/mlss_498.html">Turkey (Meleagris gallopavo)</a><br/>
<a href="mlss/mlss_441.html">Zebra Finch (Taeniopygia guttata)</a><br/>
<a href="mlss/mlss_499.html">Anole Lizard (Anolis carolinensis)</a><br/>
<h4>Zebrafish (Danio rerio)</h4>
<a href="mlss/mlss_552.html">Cod (Gadus morhua)</a><br/>
<h4>Medaka (Oryzias latipes)</h4>
<a href="mlss/mlss_225.html">Stickleback (Gasterosteus aculeatus)</a><br/>
<h4>Stickleback (Gasterosteus aculeatus)</h4>
<a href="mlss/mlss_555.html">Cod (Gadus morhua)</a><br/>
<h4>C.intestinalis (Ciona intestinalis)</h4>
<a href="mlss/mlss_569.html">C.savignyi (Ciona savignyi)</a><br/>
