<h4>Human (Homo sapiens)</h4>
Chimpanzee (Pan troglodytes)<br />
Gorilla (Gorilla gorilla)<br />
Orangutan (Pongo pygmaeus)<br />
Macaque (Macaca mulatta)<br />
Marmoset (Callithrix jacchus)<br />
Tarsier (Tarsius syrichta)<br />
Mouse Lemur (Microcebus murinus)<br />
Bushbaby (Otolemur garnettii)<br />
Tree Shrew (Tupaia belangeri)<br />
Mouse (Mus musculus)<br />
Rat (Rattus norvegicus)<br />
Kangaroo rat (Dipodomys ordii)<br />
Guinea Pig (Cavia porcellus)<br />
Squirrel (Spermophilus tridecemlineatus)<br />
Rabbit (Oryctolagus cuniculus)<br />
Pika (Ochotona princeps)<br />
Alpaca (Vicugna pacos)<br />
Dolphin (Tursiops truncatus)<br />
Cow (Bos taurus)<br />
Pig (Sus scrofa)<br />
Horse (Equus caballus)<br />
Cat (Felis catus)<br />
Giant Panda (Ailuropoda melanoleuca)<br />
Dog (Canis familiaris)<br />
Microbat (Myotis lucifugus)<br />
Megabat (Pteropus vampyrus)<br />
Hedgehog (Erinaceus europaeus)<br />
Shrew (Sorex araneus)<br />
Elephant (Loxodonta africana)<br />
Hyrax (Procavia capensis)<br />
Lesser hedgehog tenrec (Echinops telfairi)<br />
Armadillo (Dasypus novemcinctus)<br />
Sloth (Choloepus hoffmanni)<br />
Opossum (Monodelphis domestica)<br />
Wallaby (Macropus eugenii)<br />
Platypus (Ornithorhynchus anatinus)<br />
Chicken (Gallus gallus)<br />
<h4>Mouse (Mus musculus)</h4>
Rat (Rattus norvegicus)<br />
Dog (Canis familiaris)<br />
Platypus (Ornithorhynchus anatinus)<br />
Medaka (Oryzias latipes)<br />
<h4>Pig (Sus scrofa)</h4>
Cow (Bos taurus)<br />
<h4>Dog (Canis familiaris)</h4>
Giant Panda (Ailuropoda melanoleuca)<br />
<h4>Opossum (Monodelphis domestica)</h4>
Wallaby (Macropus eugenii)<br />
<h4>Chicken (Gallus gallus)</h4>
Zebra Finch (Taeniopygia guttata)<br />
<h4>Medaka (Oryzias latipes)</h4>
Stickleback (Gasterosteus aculeatus)<br />
<h4>C.intestinalis (Ciona intestinalis)</h4>
C.savignyi (Ciona savignyi)<br />
