<h4>3 neognath birds EPO</h4>
Chicken (Gallus gallus)<br />
Turkey (Meleagris gallopavo)<br />
Zebra Finch (Taeniopygia guttata)<br />

<h4>5 teleost fish EPO</h4>
Zebrafish (Danio rerio)<br />
Fugu (Takifugu rubripes)<br />
Tetraodon (Tetraodon nigroviridis)<br />
Medaka (Oryzias latipes)<br />
Stickleback (Gasterosteus aculeatus)<br />

<h4>6 primates EPO</h4>
Human (Homo sapiens)<br />
Gorilla (Gorilla gorilla)<br />
Chimpanzee (Pan troglodytes)<br />
Orangutan (Pongo abelii)<br />
Macaque (Macaca mulatta)<br />
Marmoset (Callithrix jacchus)<br />

<h4>12 eutherian mammals EPO</h4>
Human (Homo sapiens)<br />
Gorilla (Gorilla gorilla)<br />
Chimpanzee (Pan troglodytes)<br />
Orangutan (Pongo abelii)<br />
Macaque (Macaca mulatta)<br />
Marmoset (Callithrix jacchus)<br />
Mouse (Mus musculus)<br />
Rat (Rattus norvegicus)<br />
Horse (Equus caballus)<br />
Dog (Canis familiaris)<br />
Pig (Sus scrofa)<br />
Cow (Bos taurus)<br />

