<h4>4 catarrhini primates EPO</h4>
Human (Homo sapiens)<br />
Chimpanzee (Pan troglodytes)<br />
Orangutan (Pongo pygmaeus)<br />
Macaque (Macaca mulatta)<br />

<h4>9 eutherian mammals EPO</h4>
Human (Homo sapiens)<br />
Chimpanzee (Pan troglodytes)<br />
Orangutan (Pongo pygmaeus)<br />
Macaque (Macaca mulatta)<br />
Mouse (Mus musculus)<br />
Rat (Rattus norvegicus)<br />
Dog (Canis familiaris)<br />
Cow (Bos taurus)<br />
Horse (Equus caballus)<br />

<h4>29 eutherian mammals EPO</h4>
Human (Homo sapiens)<br />
Chimpanzee (Pan troglodytes)<br />
Orangutan (Pongo pygmaeus)<br />
Macaque (Macaca mulatta)<br />
Tarsier (Tarsius syrichta)<br />
Mouse Lemur (Microcebus murinus)<br />
Bushbaby (Otolemur garnettii)<br />
Mouse (Mus musculus)<br />
Rat (Rattus norvegicus)<br />
Squirrel (Spermophilus tridecemlineatus)<br />
Kangaroo rat (Dipodomys ordii)<br />
Guinea Pig (Cavia porcellus)<br />
Rabbit (Oryctolagus cuniculus)<br />
Pika (Ochotona princeps)<br />
Tree Shrew (Tupaia belangeri)<br />
Dog (Canis familiaris)<br />
Cat (Felis catus)<br />
Cow (Bos taurus)<br />
Alpaca (Vicugna pacos)<br />
Dolphin (Tursiops truncatus)<br />
Microbat (Myotis lucifugus)<br />
Megabat (Pteropus vampyrus)<br />
Horse (Equus caballus)<br />
Hedgehog (Erinaceus europaeus)<br />
Shrew (Sorex araneus)<br />
Hyrax (Procavia capensis)<br />
Elephant (Loxodonta africana)<br />
Lesser hedgehog tenrec (Echinops telfairi)<br />
Armadillo (Dasypus novemcinctus)<br />

