<h4>35 eutherian mammals EPO_LOW_COVERAGE</h4>
Human (Homo sapiens)<br />
Gorilla (Gorilla gorilla)<br />
Chimpanzee (Pan troglodytes)<br />
Orangutan (Pongo abelii)<br />
Gibbon (Nomascus leucogenys)<br />
Macaque (Macaca mulatta)<br />
Marmoset (Callithrix jacchus)<br />
Tarsier (Tarsius syrichta)<br />
Mouse Lemur (Microcebus murinus)<br />
Bushbaby (Otolemur garnettii)<br />
Mouse (Mus musculus)<br />
Rat (Rattus norvegicus)<br />
Kangaroo rat (Dipodomys ordii)<br />
Squirrel (Spermophilus tridecemlineatus)<br />
Guinea Pig (Cavia porcellus)<br />
Pika (Ochotona princeps)<br />
Rabbit (Oryctolagus cuniculus)<br />
Tree Shrew (Tupaia belangeri)<br />
Sloth (Choloepus hoffmanni)<br />
Armadillo (Dasypus novemcinctus)<br />
Lesser hedgehog tenrec (Echinops telfairi)<br />
Elephant (Loxodonta africana)<br />
Hyrax (Procavia capensis)<br />
Hedgehog (Erinaceus europaeus)<br />
Shrew (Sorex araneus)<br />
Microbat (Myotis lucifugus)<br />
Megabat (Pteropus vampyrus)<br />
Horse (Equus caballus)<br />
Cat (Felis catus)<br />
Dog (Canis familiaris)<br />
Panda (Ailuropoda melanoleuca)<br />
Dolphin (Tursiops truncatus)<br />
Pig (Sus scrofa)<br />
Cow (Bos taurus)<br />
Alpaca (Vicugna pacos)<br />

