<h4>13 amniota vertebrates Pecan</h4>
Human (Homo sapiens)<br />
Chimpanzee (Pan troglodytes)<br />
Orangutan (Pongo pygmaeus)<br />
Macaque (Macaca mulatta)<br />
Mouse (Mus musculus)<br />
Rat (Rattus norvegicus)<br />
Cow (Bos taurus)<br />
Pig (Sus scrofa)<br />
Dog (Canis familiaris)<br />
Horse (Equus caballus)<br />
Opossum (Monodelphis domestica)<br />
Platypus (Ornithorhynchus anatinus)<br />
Chicken (Gallus gallus)<br />

