<h4>19 amniota vertebrates Pecan</h4><h5>(method_link_type="PECAN" : species_set_name="amniotes")</h5>Human (Homo sapiens)<br />
Chimpanzee (Pan troglodytes)<br />
Gorilla (Gorilla gorilla)<br />
Orangutan (Pongo pygmaeus)<br />
Macaque (Macaca mulatta)<br />
Marmoset (Callithrix jacchus)<br />
Mouse (Mus musculus)<br />
Rat (Rattus norvegicus)<br />
Rabbit (Oryctolagus cuniculus)<br />
Cow (Bos taurus)<br />
Pig (Sus scrofa)<br />
Horse (Equus caballus)<br />
Dog (Canis familiaris)<br />
Opossum (Monodelphis domestica)<br />
Platypus (Ornithorhynchus anatinus)<br />
Chicken (Gallus gallus)<br />
Turkey (Meleagris gallopavo)<br />
Zebra Finch (Taeniopygia guttata)<br />
Anole Lizard (Anolis carolinensis)<br />

