<table class="spreadsheet" style="width:auto">

<tr>
<td class="bg3 left"><b><i>Homo sapiens</i></b></td>
<th class="bg4 center" style="width:5em"><i>H.sap</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Gorilla gorilla</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10048.html">YES</a></font></td><!-- H.sap -->
<th class="bg1 center" style="width:5em"><i>G.gor</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Pan troglodytes</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_10050.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- G.gor -->
<th class="bg4 center" style="width:5em"><i>P.tro</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Pongo abelii</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10030.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- G.gor -->
<td class="bg3 center">-</td><!-- P.tro -->
<th class="bg1 center" style="width:5em"><i>P.abe</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Macaca mulatta</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_10033.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- G.gor -->
<td class="bg4 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- P.abe -->
<th class="bg4 center" style="width:5em"><i>M.mul</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Callithrix jacchus</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10046.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- G.gor -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg1 center">-</td><!-- P.abe -->
<td class="bg3 center">-</td><!-- M.mul -->
<th class="bg1 center" style="width:5em"><i>C.jac</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Mus musculus</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_10034.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- G.gor -->
<td class="bg4 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- P.abe -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- C.jac -->
<th class="bg4 center" style="width:5em"><i>M.mus</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Rattus norvegicus</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10029.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- G.gor -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg1 center">-</td><!-- P.abe -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- C.jac -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10021.html">YES</a></font></td><!-- M.mus -->
<th class="bg1 center" style="width:5em"><i>R.nor</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Oryctolagus cuniculus</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_10040.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- G.gor -->
<td class="bg4 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- P.abe -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- C.jac -->
<td class="bg4 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<th class="bg4 center" style="width:5em"><i>O.cun</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Equus caballus</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10031.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- G.gor -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg1 center">-</td><!-- P.abe -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- C.jac -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg1 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- O.cun -->
<th class="bg1 center" style="width:5em"><i>E.cab</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Canis familiaris</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_10028.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- G.gor -->
<td class="bg4 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- P.abe -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- C.jac -->
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_10022.html">YES</a></font></td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10042.html">YES</a></font></td><!-- E.cab -->
<th class="bg4 center" style="width:5em"><i>C.fam</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Sus scrofa</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10037.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- G.gor -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg1 center">-</td><!-- P.abe -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- C.jac -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg1 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- E.cab -->
<td class="bg3 center">-</td><!-- C.fam -->
<th class="bg1 center" style="width:5em"><i>S.scr</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Bos taurus</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_10047.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- G.gor -->
<td class="bg4 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- P.abe -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- C.jac -->
<td class="bg4 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- E.cab -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10049.html">YES</a></font></td><!-- S.scr -->
<th class="bg4 center" style="width:5em"><i>B.tau</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Monodelphis domestica</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10026.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- G.gor -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg1 center">-</td><!-- P.abe -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- C.jac -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg1 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- E.cab -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- S.scr -->
<td class="bg3 center">-</td><!-- B.tau -->
<th class="bg1 center" style="width:5em"><i>M.dom</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Ornithorhynchus anatinus</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_10027.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- G.gor -->
<td class="bg4 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- P.abe -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- C.jac -->
<td class="bg4 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- E.cab -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center">-</td><!-- S.scr -->
<td class="bg4 center">-</td><!-- B.tau -->
<td class="bg3 center">-</td><!-- M.dom -->
<th class="bg4 center" style="width:5em"><i>O.ana</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Gallus gallus</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10035.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- G.gor -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg1 center">-</td><!-- P.abe -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- C.jac -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg1 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- E.cab -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- S.scr -->
<td class="bg3 center">-</td><!-- B.tau -->
<td class="bg1 center">-</td><!-- M.dom -->
<td class="bg3 center">-</td><!-- O.ana -->
<th class="bg1 center" style="width:5em"><i>G.gal</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Meleagris gallopavo</i></b></td>
<td class="bg4 center">-</td><!-- H.sap -->
<td class="bg3 center">-</td><!-- G.gor -->
<td class="bg4 center">-</td><!-- P.tro -->
<td class="bg3 center">-</td><!-- P.abe -->
<td class="bg4 center">-</td><!-- M.mul -->
<td class="bg3 center">-</td><!-- C.jac -->
<td class="bg4 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg4 center">-</td><!-- O.cun -->
<td class="bg3 center">-</td><!-- E.cab -->
<td class="bg4 center">-</td><!-- C.fam -->
<td class="bg3 center">-</td><!-- S.scr -->
<td class="bg4 center">-</td><!-- B.tau -->
<td class="bg3 center">-</td><!-- M.dom -->
<td class="bg4 center">-</td><!-- O.ana -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_10043.html">YES</a></font></td><!-- G.gal -->
<th class="bg4 center" style="width:5em"><i>M.gal</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Anolis carolinensis</i></b></td>
<td class="bg3 center">-</td><!-- H.sap -->
<td class="bg1 center">-</td><!-- G.gor -->
<td class="bg3 center">-</td><!-- P.tro -->
<td class="bg1 center">-</td><!-- P.abe -->
<td class="bg3 center">-</td><!-- M.mul -->
<td class="bg1 center">-</td><!-- C.jac -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg1 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- O.cun -->
<td class="bg1 center">-</td><!-- E.cab -->
<td class="bg3 center">-</td><!-- C.fam -->
<td class="bg1 center">-</td><!-- S.scr -->
<td class="bg3 center">-</td><!-- B.tau -->
<td class="bg1 center">-</td><!-- M.dom -->
<td class="bg3 center">-</td><!-- O.ana -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_10044.html">YES</a></font></td><!-- G.gal -->
<td class="bg3 center">-</td><!-- M.gal -->
<th class="bg1 center" style="width:5em"><i>A.car</i></th>
</tr>

<tr>
<th></th>
<th class="bg3 center" style="width:5em"><i>H.sap</i></th>
<th class="bg1 center" style="width:5em"><i>G.gor</i></th>
<th class="bg3 center" style="width:5em"><i>P.tro</i></th>
<th class="bg1 center" style="width:5em"><i>P.abe</i></th>
<th class="bg3 center" style="width:5em"><i>M.mul</i></th>
<th class="bg1 center" style="width:5em"><i>C.jac</i></th>
<th class="bg3 center" style="width:5em"><i>M.mus</i></th>
<th class="bg1 center" style="width:5em"><i>R.nor</i></th>
<th class="bg3 center" style="width:5em"><i>O.cun</i></th>
<th class="bg1 center" style="width:5em"><i>E.cab</i></th>
<th class="bg3 center" style="width:5em"><i>C.fam</i></th>
<th class="bg1 center" style="width:5em"><i>S.scr</i></th>
<th class="bg3 center" style="width:5em"><i>B.tau</i></th>
<th class="bg1 center" style="width:5em"><i>M.dom</i></th>
<th class="bg3 center" style="width:5em"><i>O.ana</i></th>
<th class="bg1 center" style="width:5em"><i>G.gal</i></th>
<th class="bg3 center" style="width:5em"><i>M.gal</i></th>
<th class="bg1 center" style="width:5em"><i>A.car</i></th>
<th></th>
</tr>

</table>
