<table class="spreadsheet" style="width:auto">

<tr>
<td class="bg3 left"><b><i>Homo sapiens</i></b></td>
<th class="bg4 center" style="width:5em"><i>Hsap</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Pan troglodytes</i></b></td>
<td class="bg3 center"><font color="blue">YES</font></td><!-- Hsap -->
<th class="bg1 center" style="width:5em"><i>Ptro</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Pongo pygmaeus</i></b></td>
<td class="bg4 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg3 center">-</td><!-- Ptro -->
<th class="bg4 center" style="width:5em"><i>Ppyg</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Macaca mulatta</i></b></td>
<td class="bg3 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg1 center">-</td><!-- Ptro -->
<td class="bg3 center">-</td><!-- Ppyg -->
<th class="bg1 center" style="width:5em"><i>Mmul</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Mus musculus</i></b></td>
<td class="bg4 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg3 center">-</td><!-- Ptro -->
<td class="bg4 center">-</td><!-- Ppyg -->
<td class="bg3 center">-</td><!-- Mmul -->
<th class="bg4 center" style="width:5em"><i>Mmus</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Rattus norvegicus</i></b></td>
<td class="bg3 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg1 center">-</td><!-- Ptro -->
<td class="bg3 center">-</td><!-- Ppyg -->
<td class="bg1 center">-</td><!-- Mmul -->
<td class="bg3 center"><font color="blue">YES</font></td><!-- Mmus -->
<th class="bg1 center" style="width:5em"><i>Rnor</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Canis familiaris</i></b></td>
<td class="bg4 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg3 center">-</td><!-- Ptro -->
<td class="bg4 center">-</td><!-- Ppyg -->
<td class="bg3 center">-</td><!-- Mmul -->
<td class="bg4 center"><font color="blue">YES</font></td><!-- Mmus -->
<td class="bg3 center">-</td><!-- Rnor -->
<th class="bg4 center" style="width:5em"><i>Cfam</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Bos taurus</i></b></td>
<td class="bg3 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg1 center">-</td><!-- Ptro -->
<td class="bg3 center">-</td><!-- Ppyg -->
<td class="bg1 center">-</td><!-- Mmul -->
<td class="bg3 center">-</td><!-- Mmus -->
<td class="bg1 center">-</td><!-- Rnor -->
<td class="bg3 center">-</td><!-- Cfam -->
<th class="bg1 center" style="width:5em"><i>Btau</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Equus caballus</i></b></td>
<td class="bg4 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg3 center">-</td><!-- Ptro -->
<td class="bg4 center">-</td><!-- Ppyg -->
<td class="bg3 center">-</td><!-- Mmul -->
<td class="bg4 center">-</td><!-- Mmus -->
<td class="bg3 center">-</td><!-- Rnor -->
<td class="bg4 center">-</td><!-- Cfam -->
<td class="bg3 center">-</td><!-- Btau -->
<th class="bg4 center" style="width:5em"><i>Ecab</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Monodelphis domestica</i></b></td>
<td class="bg3 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg1 center">-</td><!-- Ptro -->
<td class="bg3 center">-</td><!-- Ppyg -->
<td class="bg1 center">-</td><!-- Mmul -->
<td class="bg3 center">-</td><!-- Mmus -->
<td class="bg1 center">-</td><!-- Rnor -->
<td class="bg3 center">-</td><!-- Cfam -->
<td class="bg1 center">-</td><!-- Btau -->
<td class="bg3 center">-</td><!-- Ecab -->
<th class="bg1 center" style="width:5em"><i>Mdom</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Gallus gallus</i></b></td>
<td class="bg4 center"><font color="blue">YES</font></td><!-- Hsap -->
<td class="bg3 center">-</td><!-- Ptro -->
<td class="bg4 center">-</td><!-- Ppyg -->
<td class="bg3 center">-</td><!-- Mmul -->
<td class="bg4 center">-</td><!-- Mmus -->
<td class="bg3 center">-</td><!-- Rnor -->
<td class="bg4 center">-</td><!-- Cfam -->
<td class="bg3 center">-</td><!-- Btau -->
<td class="bg4 center">-</td><!-- Ecab -->
<td class="bg3 center">-</td><!-- Mdom -->
<th class="bg4 center" style="width:5em"><i>Ggal</i></th>
</tr>

<tr>
<th></th>
<th class="bg3 center" style="width:5em"><i>Hsap</i></th>
<th class="bg1 center" style="width:5em"><i>Ptro</i></th>
<th class="bg3 center" style="width:5em"><i>Ppyg</i></th>
<th class="bg1 center" style="width:5em"><i>Mmul</i></th>
<th class="bg3 center" style="width:5em"><i>Mmus</i></th>
<th class="bg1 center" style="width:5em"><i>Rnor</i></th>
<th class="bg3 center" style="width:5em"><i>Cfam</i></th>
<th class="bg1 center" style="width:5em"><i>Btau</i></th>
<th class="bg3 center" style="width:5em"><i>Ecab</i></th>
<th class="bg1 center" style="width:5em"><i>Mdom</i></th>
<th class="bg3 center" style="width:5em"><i>Ggal</i></th>
<th></th>
</tr>

</table>
