<h4>C.int-P.mar translated-blat-net</h4>
Lamprey (Petromyzon marinus)<br />
C.intestinalis (Ciona intestinalis)<br />

<h4>C.sav-H.sap translated-blat-net</h4>
Human (Homo sapiens)<br />
C.savignyi (Ciona savignyi)<br />

<h4>D.rer-C.int translated-blat-net</h4>
Zebrafish (Danio rerio)<br />
C.intestinalis (Ciona intestinalis)<br />

<h4>D.rer-C.sav translated-blat-net</h4>
Zebrafish (Danio rerio)<br />
C.savignyi (Ciona savignyi)<br />

<h4>D.rer-O.lat translated-blat-net</h4>
Zebrafish (Danio rerio)<br />
Medaka (Oryzias latipes)<br />

<h4>D.rer-P.mar translated-blat-net</h4>
Zebrafish (Danio rerio)<br />
Lamprey (Petromyzon marinus)<br />

<h4>D.rer-T.rub translated-blat-net</h4>
Zebrafish (Danio rerio)<br />
Fugu (Takifugu rubripes)<br />

<h4>G.acu-D.rer translated-blat-net</h4>
Zebrafish (Danio rerio)<br />
Stickleback (Gasterosteus aculeatus)<br />

<h4>G.acu-P.mar translated-blat-net</h4>
Stickleback (Gasterosteus aculeatus)<br />
Lamprey (Petromyzon marinus)<br />

<h4>G.gal-C.int translated-blat-net</h4>
Chicken (Gallus gallus)<br />
C.intestinalis (Ciona intestinalis)<br />

<h4>G.gal-C.sav translated-blat-net</h4>
Chicken (Gallus gallus)<br />
C.savignyi (Ciona savignyi)<br />

<h4>G.gal-D.rer translated-blat-net</h4>
Chicken (Gallus gallus)<br />
Zebrafish (Danio rerio)<br />

<h4>G.gal-H.sap translated-blat-net</h4>
Human (Homo sapiens)<br />
Chicken (Gallus gallus)<br />

<h4>G.gal-X.tro translated-blat-net</h4>
Chicken (Gallus gallus)<br />
X.tropicalis (Xenopus tropicalis)<br />

<h4>H.sap-A.car translated-blat-net</h4>
Human (Homo sapiens)<br />
Anole Lizard (Anolis carolinensis)<br />

<h4>H.sap-C.int translated-blat-net</h4>
Human (Homo sapiens)<br />
C.intestinalis (Ciona intestinalis)<br />

<h4>H.sap-D.rer translated-blat-net</h4>
Human (Homo sapiens)<br />
Zebrafish (Danio rerio)<br />

<h4>H.sap-G.acu translated-blat-net</h4>
Human (Homo sapiens)<br />
Stickleback (Gasterosteus aculeatus)<br />

<h4>H.sap-O.lat translated-blat-net</h4>
Human (Homo sapiens)<br />
Medaka (Oryzias latipes)<br />

<h4>H.sap-P.mar translated-blat-net</h4>
Human (Homo sapiens)<br />
Lamprey (Petromyzon marinus)<br />

<h4>H.sap-T.gut translated-blat-net</h4>
Human (Homo sapiens)<br />
Zebra Finch (Taeniopygia guttata)<br />

<h4>H.sap-T.nig translated-blat-net</h4>
Human (Homo sapiens)<br />
Tetraodon (Tetraodon nigroviridis)<br />

<h4>H.sap-T.rub translated-blat-net</h4>
Human (Homo sapiens)<br />
Fugu (Takifugu rubripes)<br />

<h4>H.sap-X.tro translated-blat-net</h4>
Human (Homo sapiens)<br />
X.tropicalis (Xenopus tropicalis)<br />

<h4>M.gal-H.sap translated-blat-net</h4>
Human (Homo sapiens)<br />
Turkey (Meleagris gallopavo)<br />

<h4>M.mus-D.rer translated-blat-net</h4>
Mouse (Mus musculus)<br />
Zebrafish (Danio rerio)<br />

<h4>M.mus-G.gal translated-blat-net</h4>
Mouse (Mus musculus)<br />
Chicken (Gallus gallus)<br />

<h4>M.mus-T.nig translated-blat-net</h4>
Mouse (Mus musculus)<br />
Tetraodon (Tetraodon nigroviridis)<br />

<h4>M.mus-T.rub translated-blat-net</h4>
Mouse (Mus musculus)<br />
Fugu (Takifugu rubripes)<br />

<h4>R.nor-D.rer translated-blat-net</h4>
Rat (Rattus norvegicus)<br />
Zebrafish (Danio rerio)<br />

<h4>R.nor-T.nig translated-blat-net</h4>
Rat (Rattus norvegicus)<br />
Tetraodon (Tetraodon nigroviridis)<br />

<h4>T.nig-D.rer translated-blat-net</h4>
Zebrafish (Danio rerio)<br />
Tetraodon (Tetraodon nigroviridis)<br />

<h4>X.tro-D.rer translated-blat-net</h4>
X.tropicalis (Xenopus tropicalis)<br />
Zebrafish (Danio rerio)<br />

<h4>X.tro-M.mus translated-blat-net</h4>
Mouse (Mus musculus)<br />
X.tropicalis (Xenopus tropicalis)<br />

<h4>X.tro-T.nig translated-blat-net</h4>
X.tropicalis (Xenopus tropicalis)<br />
Tetraodon (Tetraodon nigroviridis)<br />

