<table class="spreadsheet" style="width:auto">

<tr>
<td class="bg3 left"><b><i>Homo sapiens</i></b></td>
<th class="bg4 center" style="width:5em"><i>H.sap</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Mus musculus</i></b></td>
<td class="bg3 center">-</td><!-- H.sap -->
<th class="bg1 center" style="width:5em"><i>M.mus</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Rattus norvegicus</i></b></td>
<td class="bg4 center">-</td><!-- H.sap -->
<td class="bg3 center">-</td><!-- M.mus -->
<th class="bg4 center" style="width:5em"><i>R.nor</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Gallus gallus</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_421.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_306.html">YES</a></font></td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<th class="bg1 center" style="width:5em"><i>G.gal</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Meleagris gallopavo</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_504.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- G.gal -->
<th class="bg4 center" style="width:5em"><i>M.gal</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Taeniopygia guttata</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_413.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- G.gal -->
<td class="bg3 center">-</td><!-- M.gal -->
<th class="bg1 center" style="width:5em"><i>T.gut</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Anolis carolinensis</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_503.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- G.gal -->
<td class="bg4 center">-</td><!-- M.gal -->
<td class="bg3 center">-</td><!-- T.gut -->
<th class="bg4 center" style="width:5em"><i>A.car</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Xenopus tropicalis</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_515.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_512.html">YES</a></font></td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_513.html">YES</a></font></td><!-- G.gal -->
<td class="bg3 center">-</td><!-- M.gal -->
<td class="bg1 center">-</td><!-- T.gut -->
<td class="bg3 center">-</td><!-- A.car -->
<th class="bg1 center" style="width:5em"><i>X.tro</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Latimeria chalumnae</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_571.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- G.gal -->
<td class="bg4 center">-</td><!-- M.gal -->
<td class="bg3 center">-</td><!-- T.gut -->
<td class="bg4 center">-</td><!-- A.car -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_567.html">YES</a></font></td><!-- X.tro -->
<th class="bg4 center" style="width:5em"><i>L.cha</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Danio rerio</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_480.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_479.html">YES</a></font></td><!-- M.mus -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_481.html">YES</a></font></td><!-- R.nor -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_484.html">YES</a></font></td><!-- G.gal -->
<td class="bg3 center">-</td><!-- M.gal -->
<td class="bg1 center">-</td><!-- T.gut -->
<td class="bg3 center">-</td><!-- A.car -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_516.html">YES</a></font></td><!-- X.tro -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_568.html">YES</a></font></td><!-- L.cha -->
<th class="bg1 center" style="width:5em"><i>D.rer</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Gadus morhua</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_549.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- G.gal -->
<td class="bg4 center">-</td><!-- M.gal -->
<td class="bg3 center">-</td><!-- T.gut -->
<td class="bg4 center">-</td><!-- A.car -->
<td class="bg3 center">-</td><!-- X.tro -->
<td class="bg4 center">-</td><!-- L.cha -->
<td class="bg3 center">-</td><!-- D.rer -->
<th class="bg4 center" style="width:5em"><i>G.mor</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Takifugu rubripes</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_418.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_308.html">YES</a></font></td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- G.gal -->
<td class="bg3 center">-</td><!-- M.gal -->
<td class="bg1 center">-</td><!-- T.gut -->
<td class="bg3 center">-</td><!-- A.car -->
<td class="bg1 center">-</td><!-- X.tro -->
<td class="bg3 center">-</td><!-- L.cha -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_486.html">YES</a></font></td><!-- D.rer -->
<td class="bg3 center">-</td><!-- G.mor -->
<th class="bg1 center" style="width:5em"><i>T.rub</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Tetraodon nigroviridis</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_420.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_333.html">YES</a></font></td><!-- M.mus -->
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_335.html">YES</a></font></td><!-- R.nor -->
<td class="bg3 center">-</td><!-- G.gal -->
<td class="bg4 center">-</td><!-- M.gal -->
<td class="bg3 center">-</td><!-- T.gut -->
<td class="bg4 center">-</td><!-- A.car -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_514.html">YES</a></font></td><!-- X.tro -->
<td class="bg4 center">-</td><!-- L.cha -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_493.html">YES</a></font></td><!-- D.rer -->
<td class="bg4 center">-</td><!-- G.mor -->
<td class="bg3 center">-</td><!-- T.rub -->
<th class="bg4 center" style="width:5em"><i>T.nig</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Oryzias latipes</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_417.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- G.gal -->
<td class="bg3 center">-</td><!-- M.gal -->
<td class="bg1 center">-</td><!-- T.gut -->
<td class="bg3 center">-</td><!-- A.car -->
<td class="bg1 center">-</td><!-- X.tro -->
<td class="bg3 center">-</td><!-- L.cha -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_492.html">YES</a></font></td><!-- D.rer -->
<td class="bg3 center">-</td><!-- G.mor -->
<td class="bg1 center">-</td><!-- T.rub -->
<td class="bg3 center">-</td><!-- T.nig -->
<th class="bg1 center" style="width:5em"><i>O.lat</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Gasterosteus aculeatus</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_414.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center">-</td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- G.gal -->
<td class="bg4 center">-</td><!-- M.gal -->
<td class="bg3 center">-</td><!-- T.gut -->
<td class="bg4 center">-</td><!-- A.car -->
<td class="bg3 center">-</td><!-- X.tro -->
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_572.html">YES</a></font></td><!-- L.cha -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_491.html">YES</a></font></td><!-- D.rer -->
<td class="bg4 center">-</td><!-- G.mor -->
<td class="bg3 center">-</td><!-- T.rub -->
<td class="bg4 center">-</td><!-- T.nig -->
<td class="bg3 center">-</td><!-- O.lat -->
<th class="bg4 center" style="width:5em"><i>G.acu</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Petromyzon marinus</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_539.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center">-</td><!-- G.gal -->
<td class="bg3 center">-</td><!-- M.gal -->
<td class="bg1 center">-</td><!-- T.gut -->
<td class="bg3 center">-</td><!-- A.car -->
<td class="bg1 center">-</td><!-- X.tro -->
<td class="bg3 center">-</td><!-- L.cha -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_530.html">YES</a></font></td><!-- D.rer -->
<td class="bg3 center">-</td><!-- G.mor -->
<td class="bg1 center">-</td><!-- T.rub -->
<td class="bg3 center">-</td><!-- T.nig -->
<td class="bg1 center">-</td><!-- O.lat -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_531.html">YES</a></font></td><!-- G.acu -->
<th class="bg1 center" style="width:5em"><i>P.mar</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Ciona intestinalis</i></b></td>
<td class="bg4 center"><font color="blue"><a href="mlss/mlss_570.html">YES</a></font></td><!-- H.sap -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_564.html">YES</a></font></td><!-- M.mus -->
<td class="bg4 center">-</td><!-- R.nor -->
<td class="bg3 center">-</td><!-- G.gal -->
<td class="bg4 center">-</td><!-- M.gal -->
<td class="bg3 center">-</td><!-- T.gut -->
<td class="bg4 center">-</td><!-- A.car -->
<td class="bg3 center">-</td><!-- X.tro -->
<td class="bg4 center">-</td><!-- L.cha -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_565.html">YES</a></font></td><!-- D.rer -->
<td class="bg4 center">-</td><!-- G.mor -->
<td class="bg3 center">-</td><!-- T.rub -->
<td class="bg4 center">-</td><!-- T.nig -->
<td class="bg3 center">-</td><!-- O.lat -->
<td class="bg4 center">-</td><!-- G.acu -->
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_566.html">YES</a></font></td><!-- P.mar -->
<th class="bg4 center" style="width:5em"><i>C.int</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Ciona savignyi</i></b></td>
<td class="bg3 center"><font color="blue"><a href="mlss/mlss_422.html">YES</a></font></td><!-- H.sap -->
<td class="bg1 center">-</td><!-- M.mus -->
<td class="bg3 center">-</td><!-- R.nor -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_313.html">YES</a></font></td><!-- G.gal -->
<td class="bg3 center">-</td><!-- M.gal -->
<td class="bg1 center">-</td><!-- T.gut -->
<td class="bg3 center">-</td><!-- A.car -->
<td class="bg1 center">-</td><!-- X.tro -->
<td class="bg3 center">-</td><!-- L.cha -->
<td class="bg1 center"><font color="blue"><a href="mlss/mlss_490.html">YES</a></font></td><!-- D.rer -->
<td class="bg3 center">-</td><!-- G.mor -->
<td class="bg1 center">-</td><!-- T.rub -->
<td class="bg3 center">-</td><!-- T.nig -->
<td class="bg1 center">-</td><!-- O.lat -->
<td class="bg3 center">-</td><!-- G.acu -->
<td class="bg1 center">-</td><!-- P.mar -->
<td class="bg3 center">-</td><!-- C.int -->
<th class="bg1 center" style="width:5em"><i>C.sav</i></th>
</tr>

<tr>
<th></th>
<th class="bg3 center" style="width:5em"><i>H.sap</i></th>
<th class="bg1 center" style="width:5em"><i>M.mus</i></th>
<th class="bg3 center" style="width:5em"><i>R.nor</i></th>
<th class="bg1 center" style="width:5em"><i>G.gal</i></th>
<th class="bg3 center" style="width:5em"><i>M.gal</i></th>
<th class="bg1 center" style="width:5em"><i>T.gut</i></th>
<th class="bg3 center" style="width:5em"><i>A.car</i></th>
<th class="bg1 center" style="width:5em"><i>X.tro</i></th>
<th class="bg3 center" style="width:5em"><i>L.cha</i></th>
<th class="bg1 center" style="width:5em"><i>D.rer</i></th>
<th class="bg3 center" style="width:5em"><i>G.mor</i></th>
<th class="bg1 center" style="width:5em"><i>T.rub</i></th>
<th class="bg3 center" style="width:5em"><i>T.nig</i></th>
<th class="bg1 center" style="width:5em"><i>O.lat</i></th>
<th class="bg3 center" style="width:5em"><i>G.acu</i></th>
<th class="bg1 center" style="width:5em"><i>P.mar</i></th>
<th class="bg3 center" style="width:5em"><i>C.int</i></th>
<th class="bg1 center" style="width:5em"><i>C.sav</i></th>
<th></th>
</tr>

</table>
