<table class="spreadsheet" style="width:auto">

<tr>
<td class="bg3 left"><b><i>Anopheles gambiae</i></b></td>
<th class="bg4 center" style="width:5em"><i>A.gam</i></th>
</tr>

<tr>
<td class="bg1 left"><b><i>Aedes aegypti</i></b></td>
<td class="bg3 center"><font color="blue">YES</font></td><!-- A.gam -->
<th class="bg1 center" style="width:5em"><i>A.aeg</i></th>
</tr>

<tr>
<td class="bg3 left"><b><i>Drosophila melanogaster</i></b></td>
<td class="bg4 center"><font color="blue">YES</font></td><!-- A.gam -->
<td class="bg3 center"><font color="blue">YES</font></td><!-- A.aeg -->
<th class="bg4 center" style="width:5em"><i>D.mel</i></th>
</tr>

<tr>
<th></th>
<th class="bg3 center" style="width:5em"><i>A.gam</i></th>
<th class="bg1 center" style="width:5em"><i>A.aeg</i></th>
<th class="bg3 center" style="width:5em"><i>D.mel</i></th>
<th></th>
</tr>

</table>
