#!/usr/local/bin/perl

# Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
# Copyright [2016] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use warnings;
no warnings 'uninitialized';

use SiteDefs;

warn "Stopping nginx...\n";

die "$SiteDefs::ENSEMBL_LOGDIR/nginx.pid doesn't exist"
  unless -e "$SiteDefs::ENSEMBL_LOGDIR/nginx.pid";

my $prefix = "$SiteDefs::ENSEMBL_NGINX_CMDPREFIX " || "";
my $cmd = "${prefix}kill `cat $SiteDefs::ENSEMBL_LOGDIR/nginx.pid`";

system($cmd) == 0 or die " Could not stop nginx server: $!.\n";

1;
