#!/usr/local/bin/perl

use strict;
use warnings;

use SiteDefs;

warn "Stopping nginx...\n";

die "$SiteDefs::ENSEMBL_LOGDIR/nginx.pid doesn't exist"
  unless -e "$SiteDefs::ENSEMBL_LOGDIR/nginx.pid";

my $prefix = "$SiteDefs::ENSEMBL_NGINX_CMDPREFIX " || "";
my $cmd = "${prefix}kill `cat $SiteDefs::ENSEMBL_LOGDIR/nginx.pid`";

system($cmd) == 0 or die " Could not stop nginx server: $!.\n";

1;
