#!/usr/local/bin/perl

# Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use warnings;
no warnings 'uninitialized';

use SiteDefs;

warn "Starting nginx...\n";

die "can't find nginx root, ENSEMBL_NGINX_ROOT is not defined"
  unless defined $SiteDefs::ENSEMBL_NGINX_ROOT;

die "nginx root '$SiteDefs::ENSEMBL_NGINX_ROOT' does not exists"
  unless -d $SiteDefs::ENSEMBL_NGINX_ROOT;

die "file $SiteDefs::ENSEMBL_NGINX_ROOT/conf/nginx.conf does not exists"
  unless -e $SiteDefs::ENSEMBL_NGINX_ROOT . '/conf/nginx.conf';

die "file $SiteDefs::ENSEMBL_NGINX_ROOT/sbin/nginx is not executable"
  unless -x $SiteDefs::ENSEMBL_NGINX_ROOT . '/sbin/nginx';

my $prefix = "$SiteDefs::ENSEMBL_NGINX_CMDPREFIX " || "";
my $cmd = "$prefix$SiteDefs::ENSEMBL_NGINX_ROOT/sbin/nginx -c $SiteDefs::ENSEMBL_NGINX_ROOT/conf/nginx.conf";


system($cmd) == 0 or die " Could not start nginx server: $!.\n";

1;
