
<table class="ss autocenter" style="width:400px">
 <tbody>
  <tr class="ss_header">
   <th>Species</th>
   <th class="right">Data size (Gb)</th>
  </tr>
  <tr class="bg1">
   <td>Ailuropoda melanoleuca</td>
   <td class="right">7.1</td>
  </tr>
  <tr class="bg2">
   <td>Anas platyrhynchos</td>
   <td class="right">4.6</td>
  </tr>
  <tr class="bg1">
   <td>Anolis carolinensis</td>
   <td class="right">8.5</td>
  </tr>
  <tr class="bg2">
   <td>Astyanax mexicanus</td>
   <td class="right">5.8</td>
  </tr>
  <tr class="bg1">
   <td>Bos taurus</td>
   <td class="right">60.8</td>
  </tr>
  <tr class="bg2">
   <td>Caenorhabditis elegans</td>
   <td class="right">2.5</td>
  </tr>
  <tr class="bg1">
   <td>Callithrix jacchus</td>
   <td class="right">8.2</td>
  </tr>
  <tr class="bg2">
   <td>Canis familiaris</td>
   <td class="right">12.7</td>
  </tr>
  <tr class="bg1">
   <td>Cavia porcellus</td>
   <td class="right">7.2</td>
  </tr>
  <tr class="bg2">
   <td>Choloepus hoffmanni</td>
   <td class="right">4.1</td>
  </tr>
  <tr class="bg1">
   <td>Ciona intestinalis</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Ciona savignyi</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Danio rerio</td>
   <td class="right">10.7</td>
  </tr>
  <tr class="bg2">
   <td>Dasypus novemcinctus</td>
   <td class="right">10.8</td>
  </tr>
  <tr class="bg1">
   <td>Dipodomys ordii</td>
   <td class="right">10.2</td>
  </tr>
  <tr class="bg2">
   <td>Drosophila melanogaster</td>
   <td class="right">10.8</td>
  </tr>
  <tr class="bg1">
   <td>Echinops telfairi</td>
   <td class="right">5.8</td>
  </tr>
  <tr class="bg2">
   <td>Equus caballus</td>
   <td class="right">11.2</td>
  </tr>
  <tr class="bg1">
   <td>Erinaceus europaeus</td>
   <td class="right">7.4</td>
  </tr>
  <tr class="bg2">
   <td>Felis catus</td>
   <td class="right">8.2</td>
  </tr>
  <tr class="bg1">
   <td>Ficedula albicollis</td>
   <td class="right">7.6</td>
  </tr>
  <tr class="bg2">
   <td>Gadus morhua</td>
   <td class="right">5.1</td>
  </tr>
  <tr class="bg1">
   <td>Gallus gallus</td>
   <td class="right">16.7</td>
  </tr>
  <tr class="bg2">
   <td>Gasterosteus aculeatus</td>
   <td class="right">4.9</td>
  </tr>
  <tr class="bg1">
   <td>Gorilla gorilla</td>
   <td class="right">8.2</td>
  </tr>
  <tr class="bg2">
   <td>Homo sapiens</td>
   <td class="right">592.9</td>
  </tr>
  <tr class="bg1">
   <td>Ictidomys tridecemlineatus</td>
   <td class="right">8.0</td>
  </tr>
  <tr class="bg2">
   <td>Latimeria chalumnae</td>
   <td class="right">8.6</td>
  </tr>
  <tr class="bg1">
   <td>Lepisosteus oculatus</td>
   <td class="right">6.3</td>
  </tr>
  <tr class="bg2">
   <td>Loxodonta africana</td>
   <td class="right">7.4</td>
  </tr>
  <tr class="bg1">
   <td>Macaca mulatta</td>
   <td class="right">9.4</td>
  </tr>
  <tr class="bg2">
   <td>Macropus eugenii</td>
   <td class="right">5.9</td>
  </tr>
  <tr class="bg1">
   <td>Meleagris gallopavo</td>
   <td class="right">4.2</td>
  </tr>
  <tr class="bg2">
   <td>Microcebus murinus</td>
   <td class="right">5.4</td>
  </tr>
  <tr class="bg1">
   <td>Monodelphis domestica</td>
   <td class="right">11.4</td>
  </tr>
  <tr class="bg2">
   <td>Mus musculus</td>
   <td class="right">99.1</td>
  </tr>
  <tr class="bg1">
   <td>Mustela putorius</td>
   <td class="right">13.6</td>
  </tr>
  <tr class="bg2">
   <td>Myotis lucifugus</td>
   <td class="right">6.8</td>
  </tr>
  <tr class="bg1">
   <td>Nomascus leucogenys</td>
   <td class="right">8.9</td>
  </tr>
  <tr class="bg2">
   <td>Ochotona princeps</td>
   <td class="right">9.0</td>
  </tr>
  <tr class="bg1">
   <td>Oreochromis niloticus</td>
   <td class="right">11.6</td>
  </tr>
  <tr class="bg2">
   <td>Ornithorhynchus anatinus</td>
   <td class="right">9.2</td>
  </tr>
  <tr class="bg1">
   <td>Oryctolagus cuniculus</td>
   <td class="right">9.1</td>
  </tr>
  <tr class="bg2">
   <td>Oryzias latipes</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Otolemur garnettii</td>
   <td class="right">7.6</td>
  </tr>
  <tr class="bg2">
   <td>Ovis aries</td>
   <td class="right">35.2</td>
  </tr>
  <tr class="bg1">
   <td>Pan troglodytes</td>
   <td class="right">12.5</td>
  </tr>
  <tr class="bg2">
   <td>Papio anubis</td>
   <td class="right">9.5</td>
  </tr>
  <tr class="bg1">
   <td>Pelodiscus sinensis</td>
   <td class="right">8.1</td>
  </tr>
  <tr class="bg2">
   <td>Petromyzon marinus</td>
   <td class="right">3.9</td>
  </tr>
  <tr class="bg1">
   <td>Poecilia formosa</td>
   <td class="right">6.7</td>
  </tr>
  <tr class="bg2">
   <td>Pongo abelii</td>
   <td class="right">13.6</td>
  </tr>
  <tr class="bg1">
   <td>Procavia capensis</td>
   <td class="right">5.6</td>
  </tr>
  <tr class="bg2">
   <td>Pteropus vampyrus</td>
   <td class="right">5.7</td>
  </tr>
  <tr class="bg1">
   <td>Rattus norvegicus</td>
   <td class="right">17.0</td>
  </tr>
  <tr class="bg2">
   <td>Saccharomyces cerevisiae</td>
   <td class="right">0.5</td>
  </tr>
  <tr class="bg1">
   <td>Sarcophilus harrisii</td>
   <td class="right">9.0</td>
  </tr>
  <tr class="bg2">
   <td>Sorex araneus</td>
   <td class="right">5.4</td>
  </tr>
  <tr class="bg1">
   <td>Sus scrofa</td>
   <td class="right">26.8</td>
  </tr>
  <tr class="bg2">
   <td>Taeniopygia guttata</td>
   <td class="right">6.8</td>
  </tr>
  <tr class="bg1">
   <td>Takifugu rubripes</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg2">
   <td>Tarsius syrichta</td>
   <td class="right">5.6</td>
  </tr>
  <tr class="bg1">
   <td>Tetraodon nigroviridis</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Tupaia belangeri</td>
   <td class="right">6.5</td>
  </tr>
  <tr class="bg1">
   <td>Tursiops truncatus</td>
   <td class="right">6.2</td>
  </tr>
  <tr class="bg2">
   <td>Vicugna pacos</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg1">
   <td>Xenopus tropicalis</td>
   <td class="right">10.6</td>
  </tr>
  <tr class="bg2">
   <td>Xiphophorus maculatus</td>
   <td class="right">10.7</td>
  </tr>
  <tr>
   <th>Sub-total</th>
   <th class="right">1304.2</th>
  </tr>

  <tr>
   <th>Multi-species</th>
   <th></th>
  </tr>
  <tr class="bg1">
   <td>Ancestral</td>
   <td class="right">42.9</td>
  </tr>
  <tr class="bg2">
   <td>Archive</td>
   <td class="right">0.0</td>
  </tr>
  <tr class="bg1">
   <td>Compara</td>
   <td class="right">255.2</td>
  </tr>
  <tr class="bg2">
   <td>Mart</td>
   <td class="right">740.3</td>
  </tr>
  <tr class="bg1">
   <td>Ontology</td>
   <td class="right">0.2</td>
  </tr>
  <tr class="bg2">
   <td>Production</td>
   <td class="right">0.0</td>
  </tr>
  <tr class="bg1">
   <td>Stable</td>
   <td class="right">2.7</td>
  </tr>
  <tr class="bg2">
   <td>Website</td>
   <td class="right">0.1</td>
  </tr>
  <tr>
   <th>Total</th>
   <th class="right">2345.6</th>
  </tr>
 </tbody>
</table>
