
<table class="ss autocenter" style="width:400px">
 <tbody>
  <tr class="ss_header">
   <th>Species</th>
   <th class="right">Data size (Gb)</th>
  </tr>
  <tr class="bg1">
   <td>Acanthochromis polyacanthus</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg2">
   <td>Ailuropoda melanoleuca</td>
   <td class="right">7.1</td>
  </tr>
  <tr class="bg1">
   <td>Amphilophus citrinellus</td>
   <td class="right">3.4</td>
  </tr>
  <tr class="bg2">
   <td>Amphiprion ocellaris</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg1">
   <td>Amphiprion percula</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg2">
   <td>Anabas testudineus</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Anas platyrhynchos</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg2">
   <td>Anolis carolinensis</td>
   <td class="right">8.7</td>
  </tr>
  <tr class="bg1">
   <td>Anser brachyrhynchus</td>
   <td class="right">1.6</td>
  </tr>
  <tr class="bg2">
   <td>Aotus nancymaae</td>
   <td class="right">16.7</td>
  </tr>
  <tr class="bg1">
   <td>Apteryx haastii</td>
   <td class="right">2.3</td>
  </tr>
  <tr class="bg2">
   <td>Apteryx owenii</td>
   <td class="right">2.0</td>
  </tr>
  <tr class="bg1">
   <td>Apteryx rowi</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg2">
   <td>Astatotilapia calliptera</td>
   <td class="right">5.4</td>
  </tr>
  <tr class="bg1">
   <td>Astyanax mexicanus</td>
   <td class="right">7.0</td>
  </tr>
  <tr class="bg2">
   <td>Bison bison</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Bos indicus</td>
   <td class="right">8.1</td>
  </tr>
  <tr class="bg2">
   <td>Bos mutus</td>
   <td class="right">4.9</td>
  </tr>
  <tr class="bg1">
   <td>Bos taurus</td>
   <td class="right">118.2</td>
  </tr>
  <tr class="bg2">
   <td>Caenorhabditis elegans</td>
   <td class="right">1.9</td>
  </tr>
  <tr class="bg1">
   <td>Calidris pugnax</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg2">
   <td>Calidris pygmaea</td>
   <td class="right">2.3</td>
  </tr>
  <tr class="bg1">
   <td>Callithrix jacchus</td>
   <td class="right">17.2</td>
  </tr>
  <tr class="bg2">
   <td>Callorhinchus milii</td>
   <td class="right">4.2</td>
  </tr>
  <tr class="bg1">
   <td>Canis familiaris</td>
   <td class="right">14.8</td>
  </tr>
  <tr class="bg2">
   <td>Canis lupus</td>
   <td class="right">5.3</td>
  </tr>
  <tr class="bg1">
   <td>Capra hircus</td>
   <td class="right">36.2</td>
  </tr>
  <tr class="bg2">
   <td>Carlito syrichta</td>
   <td class="right">14.0</td>
  </tr>
  <tr class="bg1">
   <td>Castor canadensis</td>
   <td class="right">4.1</td>
  </tr>
  <tr class="bg2">
   <td>Cavia aperea</td>
   <td class="right">6.1</td>
  </tr>
  <tr class="bg1">
   <td>Cavia porcellus</td>
   <td class="right">8.0</td>
  </tr>
  <tr class="bg2">
   <td>Cebus capucinus</td>
   <td class="right">15.2</td>
  </tr>
  <tr class="bg1">
   <td>Cercocebus atys</td>
   <td class="right">20.5</td>
  </tr>
  <tr class="bg2">
   <td>Chelonoidis abingdonii</td>
   <td class="right">3.3</td>
  </tr>
  <tr class="bg1">
   <td>Chinchilla lanigera</td>
   <td class="right">8.0</td>
  </tr>
  <tr class="bg2">
   <td>Chlorocebus sabaeus</td>
   <td class="right">7.6</td>
  </tr>
  <tr class="bg1">
   <td>Choloepus hoffmanni</td>
   <td class="right">4.2</td>
  </tr>
  <tr class="bg2">
   <td>Chrysemys picta</td>
   <td class="right">7.3</td>
  </tr>
  <tr class="bg1">
   <td>Ciona intestinalis</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg2">
   <td>Ciona savignyi</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Colobus angolensis</td>
   <td class="right">17.0</td>
  </tr>
  <tr class="bg2">
   <td>Coturnix japonica</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Cricetulus griseus</td>
   <td class="right">26.1</td>
  </tr>
  <tr class="bg2">
   <td>Crocodylus porosus</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg1">
   <td>Cyanistes caeruleus</td>
   <td class="right">2.7</td>
  </tr>
  <tr class="bg2">
   <td>Cynoglossus semilaevis</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Cyprinodon variegatus</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Danio rerio</td>
   <td class="right">30.2</td>
  </tr>
  <tr class="bg1">
   <td>Dasypus novemcinctus</td>
   <td class="right">10.9</td>
  </tr>
  <tr class="bg2">
   <td>Dipodomys ordii</td>
   <td class="right">10.8</td>
  </tr>
  <tr class="bg1">
   <td>Dromaius novaehollandiae</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg2">
   <td>Drosophila melanogaster</td>
   <td class="right">1.0</td>
  </tr>
  <tr class="bg1">
   <td>Echinops telfairi</td>
   <td class="right">5.9</td>
  </tr>
  <tr class="bg2">
   <td>Electrophorus electricus</td>
   <td class="right">1.7</td>
  </tr>
  <tr class="bg1">
   <td>Eptatretus burgeri</td>
   <td class="right">5.8</td>
  </tr>
  <tr class="bg2">
   <td>Equus asinus</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg1">
   <td>Equus caballus</td>
   <td class="right">25.5</td>
  </tr>
  <tr class="bg2">
   <td>Erinaceus europaeus</td>
   <td class="right">7.5</td>
  </tr>
  <tr class="bg1">
   <td>Esox lucius</td>
   <td class="right">5.8</td>
  </tr>
  <tr class="bg2">
   <td>Felis catus</td>
   <td class="right">11.7</td>
  </tr>
  <tr class="bg1">
   <td>Ficedula albicollis</td>
   <td class="right">7.5</td>
  </tr>
  <tr class="bg2">
   <td>Fukomys damarensis</td>
   <td class="right">8.0</td>
  </tr>
  <tr class="bg1">
   <td>Fundulus heteroclitus</td>
   <td class="right">5.1</td>
  </tr>
  <tr class="bg2">
   <td>Gadus morhua</td>
   <td class="right">5.1</td>
  </tr>
  <tr class="bg1">
   <td>Gallus gallus</td>
   <td class="right">32.0</td>
  </tr>
  <tr class="bg2">
   <td>Gambusia affinis</td>
   <td class="right">3.4</td>
  </tr>
  <tr class="bg1">
   <td>Gasterosteus aculeatus</td>
   <td class="right">5.0</td>
  </tr>
  <tr class="bg2">
   <td>Gopherus agassizii</td>
   <td class="right">5.7</td>
  </tr>
  <tr class="bg1">
   <td>Gorilla gorilla</td>
   <td class="right">21.4</td>
  </tr>
  <tr class="bg2">
   <td>Haplochromis burtoni</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg1">
   <td>Heterocephalus glaber</td>
   <td class="right">15.6</td>
  </tr>
  <tr class="bg2">
   <td>Hippocampus comes</td>
   <td class="right">3.1</td>
  </tr>
  <tr class="bg1">
   <td>Homo sapiens</td>
   <td class="right">1016.4</td>
  </tr>
  <tr class="bg2">
   <td>Hucho hucho</td>
   <td class="right">8.7</td>
  </tr>
  <tr class="bg1">
   <td>Ictalurus punctatus</td>
   <td class="right">4.6</td>
  </tr>
  <tr class="bg2">
   <td>Ictidomys tridecemlineatus</td>
   <td class="right">7.2</td>
  </tr>
  <tr class="bg1">
   <td>Jaculus jaculus</td>
   <td class="right">6.9</td>
  </tr>
  <tr class="bg2">
   <td>Junco hyemalis</td>
   <td class="right">2.3</td>
  </tr>
  <tr class="bg1">
   <td>Kryptolebias marmoratus</td>
   <td class="right">3.4</td>
  </tr>
  <tr class="bg2">
   <td>Labrus bergylta</td>
   <td class="right">4.6</td>
  </tr>
  <tr class="bg1">
   <td>Lates calcarifer</td>
   <td class="right">3.3</td>
  </tr>
  <tr class="bg2">
   <td>Latimeria chalumnae</td>
   <td class="right">8.7</td>
  </tr>
  <tr class="bg1">
   <td>Lepidothrix coronata</td>
   <td class="right">1.7</td>
  </tr>
  <tr class="bg2">
   <td>Lepisosteus oculatus</td>
   <td class="right">6.3</td>
  </tr>
  <tr class="bg1">
   <td>Lonchura striata</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg2">
   <td>Loxodonta africana</td>
   <td class="right">7.5</td>
  </tr>
  <tr class="bg1">
   <td>Macaca fascicularis</td>
   <td class="right">21.2</td>
  </tr>
  <tr class="bg2">
   <td>Macaca mulatta</td>
   <td class="right">61.4</td>
  </tr>
  <tr class="bg1">
   <td>Macaca nemestrina</td>
   <td class="right">21.0</td>
  </tr>
  <tr class="bg2">
   <td>Manacus vitellinus</td>
   <td class="right">2.1</td>
  </tr>
  <tr class="bg1">
   <td>Mandrillus leucophaeus</td>
   <td class="right">17.7</td>
  </tr>
  <tr class="bg2">
   <td>Marmota marmota</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg1">
   <td>Mastacembelus armatus</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg2">
   <td>Master schema</td>
   <td class="right">0.0</td>
  </tr>
  <tr class="bg1">
   <td>Maylandia zebra</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg2">
   <td>Meleagris gallopavo</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Melopsittacus undulatus</td>
   <td class="right">1.8</td>
  </tr>
  <tr class="bg2">
   <td>Meriones unguiculatus</td>
   <td class="right">4.2</td>
  </tr>
  <tr class="bg1">
   <td>Mesocricetus auratus</td>
   <td class="right">6.6</td>
  </tr>
  <tr class="bg2">
   <td>Microcebus murinus</td>
   <td class="right">14.3</td>
  </tr>
  <tr class="bg1">
   <td>Microtus ochrogaster</td>
   <td class="right">6.5</td>
  </tr>
  <tr class="bg2">
   <td>Mola mola</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg1">
   <td>Monodelphis domestica</td>
   <td class="right">11.4</td>
  </tr>
  <tr class="bg2">
   <td>Monopterus albus</td>
   <td class="right">3.9</td>
  </tr>
  <tr class="bg1">
   <td>Mus caroli</td>
   <td class="right">4.9</td>
  </tr>
  <tr class="bg2">
   <td>Mus musculus</td>
   <td class="right">405.2</td>
  </tr>
  <tr class="bg1">
   <td>Mus pahari</td>
   <td class="right">4.8</td>
  </tr>
  <tr class="bg2">
   <td>Mus spicilegus</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg1">
   <td>Mus spretus</td>
   <td class="right">15.2</td>
  </tr>
  <tr class="bg2">
   <td>Mustela putorius</td>
   <td class="right">13.7</td>
  </tr>
  <tr class="bg1">
   <td>Myotis lucifugus</td>
   <td class="right">6.9</td>
  </tr>
  <tr class="bg2">
   <td>Nannospalax galili</td>
   <td class="right">8.0</td>
  </tr>
  <tr class="bg1">
   <td>Neolamprologus brichardi</td>
   <td class="right">3.7</td>
  </tr>
  <tr class="bg2">
   <td>Neovison vison</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg1">
   <td>Nomascus leucogenys</td>
   <td class="right">18.4</td>
  </tr>
  <tr class="bg2">
   <td>Notamacropus eugenii</td>
   <td class="right">5.9</td>
  </tr>
  <tr class="bg1">
   <td>Notechis scutatus</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg2">
   <td>Nothoprocta perdicaria</td>
   <td class="right">1.4</td>
  </tr>
  <tr class="bg1">
   <td>Numida meleagris</td>
   <td class="right">2.7</td>
  </tr>
  <tr class="bg2">
   <td>Ochotona princeps</td>
   <td class="right">9.0</td>
  </tr>
  <tr class="bg1">
   <td>Octodon degus</td>
   <td class="right">7.8</td>
  </tr>
  <tr class="bg2">
   <td>Oreochromis niloticus</td>
   <td class="right">11.8</td>
  </tr>
  <tr class="bg1">
   <td>Ornithorhynchus anatinus</td>
   <td class="right">8.6</td>
  </tr>
  <tr class="bg2">
   <td>Oryctolagus cuniculus</td>
   <td class="right">9.3</td>
  </tr>
  <tr class="bg1">
   <td>Oryzias latipes</td>
   <td class="right">14.0</td>
  </tr>
  <tr class="bg2">
   <td>Oryzias melastigma</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg1">
   <td>Otolemur garnettii</td>
   <td class="right">7.7</td>
  </tr>
  <tr class="bg2">
   <td>Ovis aries</td>
   <td class="right">60.3</td>
  </tr>
  <tr class="bg1">
   <td>Pan paniscus</td>
   <td class="right">22.0</td>
  </tr>
  <tr class="bg2">
   <td>Pan troglodytes</td>
   <td class="right">27.3</td>
  </tr>
  <tr class="bg1">
   <td>Panthera pardus</td>
   <td class="right">5.9</td>
  </tr>
  <tr class="bg2">
   <td>Panthera tigris</td>
   <td class="right">5.5</td>
  </tr>
  <tr class="bg1">
   <td>Papio anubis</td>
   <td class="right">20.2</td>
  </tr>
  <tr class="bg2">
   <td>Paramormyrops kingsleyae</td>
   <td class="right">6.5</td>
  </tr>
  <tr class="bg1">
   <td>Parus major</td>
   <td class="right">2.7</td>
  </tr>
  <tr class="bg2">
   <td>Pelodiscus sinensis</td>
   <td class="right">8.2</td>
  </tr>
  <tr class="bg1">
   <td>Periophthalmus magnuspinnatus</td>
   <td class="right">3.2</td>
  </tr>
  <tr class="bg2">
   <td>Peromyscus maniculatus</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Petromyzon marinus</td>
   <td class="right">3.9</td>
  </tr>
  <tr class="bg2">
   <td>Phascolarctos cinereus</td>
   <td class="right">5.3</td>
  </tr>
  <tr class="bg1">
   <td>Piliocolobus tephrosceles</td>
   <td class="right">16.8</td>
  </tr>
  <tr class="bg2">
   <td>Poecilia formosa</td>
   <td class="right">6.6</td>
  </tr>
  <tr class="bg1">
   <td>Poecilia latipinna</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg2">
   <td>Poecilia mexicana</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Poecilia reticulata</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg2">
   <td>Pogona vitticeps</td>
   <td class="right">5.2</td>
  </tr>
  <tr class="bg1">
   <td>Pongo abelii</td>
   <td class="right">15.2</td>
  </tr>
  <tr class="bg2">
   <td>Procavia capensis</td>
   <td class="right">5.6</td>
  </tr>
  <tr class="bg1">
   <td>Prolemur simus</td>
   <td class="right">10.9</td>
  </tr>
  <tr class="bg2">
   <td>Propithecus coquereli</td>
   <td class="right">11.8</td>
  </tr>
  <tr class="bg1">
   <td>Pteropus vampyrus</td>
   <td class="right">5.8</td>
  </tr>
  <tr class="bg2">
   <td>Pundamilia nyererei</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Pygocentrus nattereri</td>
   <td class="right">5.2</td>
  </tr>
  <tr class="bg2">
   <td>Rattus norvegicus</td>
   <td class="right">20.2</td>
  </tr>
  <tr class="bg1">
   <td>Rhinopithecus bieti</td>
   <td class="right">19.0</td>
  </tr>
  <tr class="bg2">
   <td>Rhinopithecus roxellana</td>
   <td class="right">18.7</td>
  </tr>
  <tr class="bg1">
   <td>Saccharomyces cerevisiae</td>
   <td class="right">0.6</td>
  </tr>
  <tr class="bg2">
   <td>Saimiri boliviensis</td>
   <td class="right">15.3</td>
  </tr>
  <tr class="bg1">
   <td>Salvator merianae</td>
   <td class="right">3.4</td>
  </tr>
  <tr class="bg2">
   <td>Sarcophilus harrisii</td>
   <td class="right">9.0</td>
  </tr>
  <tr class="bg1">
   <td>Scleropages formosus</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg2">
   <td>Scophthalmus maximus</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg1">
   <td>Serinus canaria</td>
   <td class="right">2.3</td>
  </tr>
  <tr class="bg2">
   <td>Seriola dumerili</td>
   <td class="right">3.6</td>
  </tr>
  <tr class="bg1">
   <td>Seriola lalandi</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg2">
   <td>Sorex araneus</td>
   <td class="right">5.5</td>
  </tr>
  <tr class="bg1">
   <td>Spermophilus dauricus</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg2">
   <td>Sphenodon punctatus</td>
   <td class="right">8.0</td>
  </tr>
  <tr class="bg1">
   <td>Stegastes partitus</td>
   <td class="right">3.7</td>
  </tr>
  <tr class="bg2">
   <td>Sus scrofa</td>
   <td class="right">90.1</td>
  </tr>
  <tr class="bg1">
   <td>Taeniopygia guttata</td>
   <td class="right">6.7</td>
  </tr>
  <tr class="bg2">
   <td>Takifugu rubripes</td>
   <td class="right">3.1</td>
  </tr>
  <tr class="bg1">
   <td>Tetraodon nigroviridis</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Theropithecus gelada</td>
   <td class="right">16.3</td>
  </tr>
  <tr class="bg1">
   <td>Tupaia belangeri</td>
   <td class="right">6.5</td>
  </tr>
  <tr class="bg2">
   <td>Tursiops truncatus</td>
   <td class="right">6.3</td>
  </tr>
  <tr class="bg1">
   <td>Urocitellus parryii</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg2">
   <td>Ursus americanus</td>
   <td class="right">5.1</td>
  </tr>
  <tr class="bg1">
   <td>Ursus maritimus</td>
   <td class="right">4.9</td>
  </tr>
  <tr class="bg2">
   <td>Vicugna pacos</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg1">
   <td>Vombatus ursinus</td>
   <td class="right">6.9</td>
  </tr>
  <tr class="bg2">
   <td>Vulpes vulpes</td>
   <td class="right">7.6</td>
  </tr>
  <tr class="bg1">
   <td>Xenopus tropicalis</td>
   <td class="right">10.9</td>
  </tr>
  <tr class="bg2">
   <td>Xiphophorus couchianus</td>
   <td class="right">2.9</td>
  </tr>
  <tr class="bg1">
   <td>Xiphophorus maculatus</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg2">
   <td>Zonotrichia albicollis</td>
   <td class="right">2.1</td>
  </tr>
  <tr>
   <th>Sub-total</th>
   <th class="right">3141.0</th>
  </tr>

  <tr>
   <th>Multi-species</th>
   <th></th>
  </tr>
  <tr class="bg1">
   <td>Ancestral</td>
   <td class="right">166.7</td>
  </tr>
  <tr class="bg2">
   <td>Archive</td>
   <td class="right">0.0</td>
  </tr>
  <tr class="bg1">
   <td>Compara</td>
   <td class="right">596.4</td>
  </tr>
  <tr class="bg2">
   <td>Mart</td>
   <td class="right">2806.2</td>
  </tr>
  <tr class="bg1">
   <td>Metadata</td>
   <td class="right">7.3</td>
  </tr>
  <tr class="bg2">
   <td>Ontology</td>
   <td class="right">1.4</td>
  </tr>
  <tr class="bg1">
   <td>Production</td>
   <td class="right">0.0</td>
  </tr>
  <tr class="bg2">
   <td>Stable</td>
   <td class="right">55.8</td>
  </tr>
  <tr class="bg1">
   <td>Website</td>
   <td class="right">0.5</td>
  </tr>
  <tr>
   <th>Total</th>
   <th class="right">6775.2</th>
  </tr>
 </tbody>
</table>
