
<table class="ss autocenter" style="width:400px">
 <tbody>
  <tr class="ss_header">
   <th>Species</th>
   <th class="right">Data size (Gb)</th>
  </tr>
  <tr class="bg1">
   <td>Acanthochromis polyacanthus</td>
   <td class="right">4.8</td>
  </tr>
  <tr class="bg2">
   <td>Accipiter nisus</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg1">
   <td>Ailuropoda melanoleuca</td>
   <td class="right">5.6</td>
  </tr>
  <tr class="bg2">
   <td>Amazona collaria</td>
   <td class="right">2.0</td>
  </tr>
  <tr class="bg1">
   <td>Amphilophus citrinellus</td>
   <td class="right">3.5</td>
  </tr>
  <tr class="bg2">
   <td>Amphiprion ocellaris</td>
   <td class="right">1.8</td>
  </tr>
  <tr class="bg1">
   <td>Amphiprion percula</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg2">
   <td>Anabas testudineus</td>
   <td class="right">1.7</td>
  </tr>
  <tr class="bg1">
   <td>Anas platyrhynchos</td>
   <td class="right">6.4</td>
  </tr>
  <tr class="bg2">
   <td>Anas zonorhyncha</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg1">
   <td>Anolis carolinensis</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg2">
   <td>Anser brachyrhynchus</td>
   <td class="right">1.6</td>
  </tr>
  <tr class="bg1">
   <td>Anser cygnoides</td>
   <td class="right">2.6</td>
  </tr>
  <tr class="bg2">
   <td>Aotus nancymaae</td>
   <td class="right">17.4</td>
  </tr>
  <tr class="bg1">
   <td>Apteryx haastii</td>
   <td class="right">2.4</td>
  </tr>
  <tr class="bg2">
   <td>Apteryx owenii</td>
   <td class="right">2.1</td>
  </tr>
  <tr class="bg1">
   <td>Apteryx rowi</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg2">
   <td>Aquila chrysaetos</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg1">
   <td>Astatotilapia calliptera</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg2">
   <td>Astyanax mexicanus</td>
   <td class="right">10.8</td>
  </tr>
  <tr class="bg1">
   <td>Athene cunicularia</td>
   <td class="right">1.8</td>
  </tr>
  <tr class="bg2">
   <td>Balaenoptera musculus</td>
   <td class="right">3.4</td>
  </tr>
  <tr class="bg1">
   <td>Betta splendens</td>
   <td class="right">2.9</td>
  </tr>
  <tr class="bg2">
   <td>Bison bison</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg1">
   <td>Bos grunniens</td>
   <td class="right">6.9</td>
  </tr>
  <tr class="bg2">
   <td>Bos indicus</td>
   <td class="right">8.3</td>
  </tr>
  <tr class="bg1">
   <td>Bos mutus</td>
   <td class="right">5.0</td>
  </tr>
  <tr class="bg2">
   <td>Bos taurus</td>
   <td class="right">89.7</td>
  </tr>
  <tr class="bg1">
   <td>Bubo bubo</td>
   <td class="right">1.8</td>
  </tr>
  <tr class="bg2">
   <td>Buteo japonicus</td>
   <td class="right">1.9</td>
  </tr>
  <tr class="bg1">
   <td>Caenorhabditis elegans</td>
   <td class="right">2.0</td>
  </tr>
  <tr class="bg2">
   <td>Cairina moschata</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Calidris pugnax</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg2">
   <td>Calidris pygmaea</td>
   <td class="right">2.4</td>
  </tr>
  <tr class="bg1">
   <td>Callithrix jacchus</td>
   <td class="right">19.8</td>
  </tr>
  <tr class="bg2">
   <td>Callorhinchus milii</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg1">
   <td>Camarhynchus parvulus</td>
   <td class="right">2.0</td>
  </tr>
  <tr class="bg2">
   <td>Camelus dromedarius</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Canis lupus</td>
   <td class="right">90.6</td>
  </tr>
  <tr class="bg2">
   <td>Capra hircus</td>
   <td class="right">43.1</td>
  </tr>
  <tr class="bg1">
   <td>Carassius auratus</td>
   <td class="right">7.8</td>
  </tr>
  <tr class="bg2">
   <td>Carlito syrichta</td>
   <td class="right">14.7</td>
  </tr>
  <tr class="bg1">
   <td>Castor canadensis</td>
   <td class="right">4.1</td>
  </tr>
  <tr class="bg2">
   <td>Catagonus wagneri</td>
   <td class="right">4.8</td>
  </tr>
  <tr class="bg1">
   <td>Catharus ustulatus</td>
   <td class="right">2.1</td>
  </tr>
  <tr class="bg2">
   <td>Cavia aperea</td>
   <td class="right">6.1</td>
  </tr>
  <tr class="bg1">
   <td>Cavia porcellus</td>
   <td class="right">8.1</td>
  </tr>
  <tr class="bg2">
   <td>Cebus imitator</td>
   <td class="right">6.0</td>
  </tr>
  <tr class="bg1">
   <td>Cercocebus atys</td>
   <td class="right">20.6</td>
  </tr>
  <tr class="bg2">
   <td>Cervus hanglu</td>
   <td class="right">5.8</td>
  </tr>
  <tr class="bg1">
   <td>Chelonoidis abingdonii</td>
   <td class="right">3.3</td>
  </tr>
  <tr class="bg2">
   <td>Chelydra serpentina</td>
   <td class="right">3.4</td>
  </tr>
  <tr class="bg1">
   <td>Chinchilla lanigera</td>
   <td class="right">8.1</td>
  </tr>
  <tr class="bg2">
   <td>Chlorocebus sabaeus</td>
   <td class="right">7.7</td>
  </tr>
  <tr class="bg1">
   <td>Choloepus hoffmanni</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Chrysemys picta</td>
   <td class="right">7.4</td>
  </tr>
  <tr class="bg1">
   <td>Chrysolophus pictus</td>
   <td class="right">1.6</td>
  </tr>
  <tr class="bg2">
   <td>Ciona intestinalis</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg1">
   <td>Ciona savignyi</td>
   <td class="right">2.9</td>
  </tr>
  <tr class="bg2">
   <td>Clupea harengus</td>
   <td class="right">2.1</td>
  </tr>
  <tr class="bg1">
   <td>Colobus angolensis</td>
   <td class="right">17.2</td>
  </tr>
  <tr class="bg2">
   <td>Corvus moneduloides</td>
   <td class="right">2.7</td>
  </tr>
  <tr class="bg1">
   <td>Cottoperca gobio</td>
   <td class="right">2.3</td>
  </tr>
  <tr class="bg2">
   <td>Coturnix japonica</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Cricetulus griseus</td>
   <td class="right">28.2</td>
  </tr>
  <tr class="bg2">
   <td>Crocodylus porosus</td>
   <td class="right">3.1</td>
  </tr>
  <tr class="bg1">
   <td>Cyanistes caeruleus</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg2">
   <td>Cyclopterus lumpus</td>
   <td class="right">1.4</td>
  </tr>
  <tr class="bg1">
   <td>Cynoglossus semilaevis</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg2">
   <td>Cyprinodon variegatus</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg1">
   <td>Cyprinus carpio</td>
   <td class="right">44.1</td>
  </tr>
  <tr class="bg2">
   <td>Danio rerio</td>
   <td class="right">26.9</td>
  </tr>
  <tr class="bg1">
   <td>Dasypus novemcinctus</td>
   <td class="right">11.0</td>
  </tr>
  <tr class="bg2">
   <td>Delphinapterus leucas</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Denticeps clupeoides</td>
   <td class="right">2.9</td>
  </tr>
  <tr class="bg2">
   <td>Dicentrarchus labrax</td>
   <td class="right">3.5</td>
  </tr>
  <tr class="bg1">
   <td>Dipodomys ordii</td>
   <td class="right">10.9</td>
  </tr>
  <tr class="bg2">
   <td>Dromaius novaehollandiae</td>
   <td class="right">2.9</td>
  </tr>
  <tr class="bg1">
   <td>Drosophila melanogaster</td>
   <td class="right">1.3</td>
  </tr>
  <tr class="bg2">
   <td>Echeneis naucrates</td>
   <td class="right">1.6</td>
  </tr>
  <tr class="bg1">
   <td>Echinops telfairi</td>
   <td class="right">6.0</td>
  </tr>
  <tr class="bg2">
   <td>Electrophorus electricus</td>
   <td class="right">1.8</td>
  </tr>
  <tr class="bg1">
   <td>Eptatretus burgeri</td>
   <td class="right">5.9</td>
  </tr>
  <tr class="bg2">
   <td>Equus asinus</td>
   <td class="right">8.7</td>
  </tr>
  <tr class="bg1">
   <td>Equus caballus</td>
   <td class="right">89.4</td>
  </tr>
  <tr class="bg2">
   <td>Erinaceus europaeus</td>
   <td class="right">7.7</td>
  </tr>
  <tr class="bg1">
   <td>Erpetoichthys calabaricus</td>
   <td class="right">5.5</td>
  </tr>
  <tr class="bg2">
   <td>Erythrura gouldiae</td>
   <td class="right">1.7</td>
  </tr>
  <tr class="bg1">
   <td>Esox lucius</td>
   <td class="right">5.2</td>
  </tr>
  <tr class="bg2">
   <td>Falco tinnunculus</td>
   <td class="right">2.1</td>
  </tr>
  <tr class="bg1">
   <td>Felis catus</td>
   <td class="right">11.8</td>
  </tr>
  <tr class="bg2">
   <td>Ficedula albicollis</td>
   <td class="right">3.9</td>
  </tr>
  <tr class="bg1">
   <td>Fukomys damarensis</td>
   <td class="right">8.1</td>
  </tr>
  <tr class="bg2">
   <td>Fundulus heteroclitus</td>
   <td class="right">5.2</td>
  </tr>
  <tr class="bg1">
   <td>Gadus morhua</td>
   <td class="right">5.7</td>
  </tr>
  <tr class="bg2">
   <td>Gallus gallus</td>
   <td class="right">101.8</td>
  </tr>
  <tr class="bg1">
   <td>Gambusia affinis</td>
   <td class="right">3.4</td>
  </tr>
  <tr class="bg2">
   <td>Gasterosteus aculeatus</td>
   <td class="right">18.5</td>
  </tr>
  <tr class="bg1">
   <td>Geospiza fortis</td>
   <td class="right">1.9</td>
  </tr>
  <tr class="bg2">
   <td>Gopherus agassizii</td>
   <td class="right">5.9</td>
  </tr>
  <tr class="bg1">
   <td>Gopherus evgoodei</td>
   <td class="right">3.7</td>
  </tr>
  <tr class="bg2">
   <td>Gorilla gorilla</td>
   <td class="right">22.4</td>
  </tr>
  <tr class="bg1">
   <td>Gouania willdenowi</td>
   <td class="right">2.5</td>
  </tr>
  <tr class="bg2">
   <td>Haplochromis burtoni</td>
   <td class="right">4.6</td>
  </tr>
  <tr class="bg1">
   <td>Heterocephalus glaber</td>
   <td class="right">18.2</td>
  </tr>
  <tr class="bg2">
   <td>Hippocampus comes</td>
   <td class="right">3.2</td>
  </tr>
  <tr class="bg1">
   <td>Homo sapiens</td>
   <td class="right">2460.4</td>
  </tr>
  <tr class="bg2">
   <td>Hucho hucho</td>
   <td class="right">9.0</td>
  </tr>
  <tr class="bg1">
   <td>Ictalurus punctatus</td>
   <td class="right">2.7</td>
  </tr>
  <tr class="bg2">
   <td>Ictidomys tridecemlineatus</td>
   <td class="right">7.3</td>
  </tr>
  <tr class="bg1">
   <td>Jaculus jaculus</td>
   <td class="right">7.0</td>
  </tr>
  <tr class="bg2">
   <td>Junco hyemalis</td>
   <td class="right">2.3</td>
  </tr>
  <tr class="bg1">
   <td>Kryptolebias marmoratus</td>
   <td class="right">3.5</td>
  </tr>
  <tr class="bg2">
   <td>Labrus bergylta</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg1">
   <td>Larimichthys crocea</td>
   <td class="right">4.9</td>
  </tr>
  <tr class="bg2">
   <td>Lates calcarifer</td>
   <td class="right">3.4</td>
  </tr>
  <tr class="bg1">
   <td>Laticauda laticaudata</td>
   <td class="right">2.6</td>
  </tr>
  <tr class="bg2">
   <td>Latimeria chalumnae</td>
   <td class="right">8.7</td>
  </tr>
  <tr class="bg1">
   <td>Lepidothrix coronata</td>
   <td class="right">1.8</td>
  </tr>
  <tr class="bg2">
   <td>Lepisosteus oculatus</td>
   <td class="right">6.4</td>
  </tr>
  <tr class="bg1">
   <td>Leptobrachium leishanense</td>
   <td class="right">6.5</td>
  </tr>
  <tr class="bg2">
   <td>Lonchura striata</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg1">
   <td>Loxodonta africana</td>
   <td class="right">7.5</td>
  </tr>
  <tr class="bg2">
   <td>Lynx canadensis</td>
   <td class="right">4.9</td>
  </tr>
  <tr class="bg1">
   <td>Macaca fascicularis</td>
   <td class="right">7.7</td>
  </tr>
  <tr class="bg2">
   <td>Macaca mulatta</td>
   <td class="right">29.5</td>
  </tr>
  <tr class="bg1">
   <td>Macaca nemestrina</td>
   <td class="right">21.2</td>
  </tr>
  <tr class="bg2">
   <td>Malurus cyaneus</td>
   <td class="right">1.6</td>
  </tr>
  <tr class="bg1">
   <td>Manacus vitellinus</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg2">
   <td>Mandrillus leucophaeus</td>
   <td class="right">18.6</td>
  </tr>
  <tr class="bg1">
   <td>Marmota marmota</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg2">
   <td>Mastacembelus armatus</td>
   <td class="right">2.0</td>
  </tr>
  <tr class="bg1">
   <td>Maylandia zebra</td>
   <td class="right">4.8</td>
  </tr>
  <tr class="bg2">
   <td>Meleagris gallopavo</td>
   <td class="right">3.6</td>
  </tr>
  <tr class="bg1">
   <td>Melopsittacus undulatus</td>
   <td class="right">2.1</td>
  </tr>
  <tr class="bg2">
   <td>Meriones unguiculatus</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Mesocricetus auratus</td>
   <td class="right">6.7</td>
  </tr>
  <tr class="bg2">
   <td>Microcebus murinus</td>
   <td class="right">14.4</td>
  </tr>
  <tr class="bg1">
   <td>Microtus ochrogaster</td>
   <td class="right">6.5</td>
  </tr>
  <tr class="bg2">
   <td>Mola mola</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg1">
   <td>Monodelphis domestica</td>
   <td class="right">8.5</td>
  </tr>
  <tr class="bg2">
   <td>Monodon monoceros</td>
   <td class="right">3.7</td>
  </tr>
  <tr class="bg1">
   <td>Monopterus albus</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg2">
   <td>Moschus moschiferus</td>
   <td class="right">5.3</td>
  </tr>
  <tr class="bg1">
   <td>Mus caroli</td>
   <td class="right">5.0</td>
  </tr>
  <tr class="bg2">
   <td>Mus musculus</td>
   <td class="right">415.3</td>
  </tr>
  <tr class="bg1">
   <td>Mus pahari</td>
   <td class="right">4.9</td>
  </tr>
  <tr class="bg2">
   <td>Mus spicilegus</td>
   <td class="right">4.6</td>
  </tr>
  <tr class="bg1">
   <td>Mus spretus</td>
   <td class="right">15.5</td>
  </tr>
  <tr class="bg2">
   <td>Mustela putorius</td>
   <td class="right">13.8</td>
  </tr>
  <tr class="bg1">
   <td>Myotis lucifugus</td>
   <td class="right">7.0</td>
  </tr>
  <tr class="bg2">
   <td>Myripristis murdjan</td>
   <td class="right">1.9</td>
  </tr>
  <tr class="bg1">
   <td>Naja naja</td>
   <td class="right">2.9</td>
  </tr>
  <tr class="bg2">
   <td>Nannospalax galili</td>
   <td class="right">8.2</td>
  </tr>
  <tr class="bg1">
   <td>Neogobius melanostomus</td>
   <td class="right">2.1</td>
  </tr>
  <tr class="bg2">
   <td>Neolamprologus brichardi</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Neovison vison</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg2">
   <td>Nomascus leucogenys</td>
   <td class="right">17.9</td>
  </tr>
  <tr class="bg1">
   <td>Notamacropus eugenii</td>
   <td class="right">6.2</td>
  </tr>
  <tr class="bg2">
   <td>Notechis scutatus</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg1">
   <td>Nothobranchius furzeri</td>
   <td class="right">5.1</td>
  </tr>
  <tr class="bg2">
   <td>Nothoprocta perdicaria</td>
   <td class="right">1.4</td>
  </tr>
  <tr class="bg1">
   <td>Numida meleagris</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg2">
   <td>Ochotona princeps</td>
   <td class="right">9.2</td>
  </tr>
  <tr class="bg1">
   <td>Octodon degus</td>
   <td class="right">7.9</td>
  </tr>
  <tr class="bg2">
   <td>Oncorhynchus kisutch</td>
   <td class="right">10.8</td>
  </tr>
  <tr class="bg1">
   <td>Oncorhynchus mykiss</td>
   <td class="right">14.4</td>
  </tr>
  <tr class="bg2">
   <td>Oncorhynchus tshawytscha</td>
   <td class="right">16.3</td>
  </tr>
  <tr class="bg1">
   <td>Oreochromis aureus</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Oreochromis niloticus</td>
   <td class="right">6.2</td>
  </tr>
  <tr class="bg1">
   <td>Ornithorhynchus anatinus</td>
   <td class="right">6.7</td>
  </tr>
  <tr class="bg2">
   <td>Oryctolagus cuniculus</td>
   <td class="right">11.4</td>
  </tr>
  <tr class="bg1">
   <td>Oryzias javanicus</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg2">
   <td>Oryzias latipes</td>
   <td class="right">14.2</td>
  </tr>
  <tr class="bg1">
   <td>Oryzias melastigma</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Oryzias sinensis</td>
   <td class="right">5.0</td>
  </tr>
  <tr class="bg1">
   <td>Otolemur garnettii</td>
   <td class="right">7.7</td>
  </tr>
  <tr class="bg2">
   <td>Otus sunia</td>
   <td class="right">1.9</td>
  </tr>
  <tr class="bg1">
   <td>Ovis aries</td>
   <td class="right">142.1</td>
  </tr>
  <tr class="bg2">
   <td>Pan paniscus</td>
   <td class="right">23.0</td>
  </tr>
  <tr class="bg1">
   <td>Pan troglodytes</td>
   <td class="right">26.8</td>
  </tr>
  <tr class="bg2">
   <td>Panthera leo</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Panthera pardus</td>
   <td class="right">6.0</td>
  </tr>
  <tr class="bg2">
   <td>Panthera tigris</td>
   <td class="right">5.6</td>
  </tr>
  <tr class="bg1">
   <td>Papio anubis</td>
   <td class="right">22.1</td>
  </tr>
  <tr class="bg2">
   <td>Parambassis ranga</td>
   <td class="right">1.8</td>
  </tr>
  <tr class="bg1">
   <td>Paramormyrops kingsleyae</td>
   <td class="right">6.6</td>
  </tr>
  <tr class="bg2">
   <td>Parus major</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Pavo cristatus</td>
   <td class="right">1.9</td>
  </tr>
  <tr class="bg2">
   <td>Pelodiscus sinensis</td>
   <td class="right">8.2</td>
  </tr>
  <tr class="bg1">
   <td>Pelusios castaneus</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg2">
   <td>Periophthalmus magnuspinnatus</td>
   <td class="right">3.2</td>
  </tr>
  <tr class="bg1">
   <td>Peromyscus maniculatus</td>
   <td class="right">3.9</td>
  </tr>
  <tr class="bg2">
   <td>Petromyzon marinus</td>
   <td class="right">4.0</td>
  </tr>
  <tr class="bg1">
   <td>Phascolarctos cinereus</td>
   <td class="right">5.4</td>
  </tr>
  <tr class="bg2">
   <td>Phasianus colchicus</td>
   <td class="right">2.1</td>
  </tr>
  <tr class="bg1">
   <td>Phocoena sinus</td>
   <td class="right">3.6</td>
  </tr>
  <tr class="bg2">
   <td>Physeter catodon</td>
   <td class="right">4.1</td>
  </tr>
  <tr class="bg1">
   <td>Piliocolobus tephrosceles</td>
   <td class="right">17.0</td>
  </tr>
  <tr class="bg2">
   <td>Podarcis muralis</td>
   <td class="right">3.2</td>
  </tr>
  <tr class="bg1">
   <td>Poecilia formosa</td>
   <td class="right">6.7</td>
  </tr>
  <tr class="bg2">
   <td>Poecilia latipinna</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Poecilia mexicana</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg2">
   <td>Poecilia reticulata</td>
   <td class="right">4.8</td>
  </tr>
  <tr class="bg1">
   <td>Pogona vitticeps</td>
   <td class="right">5.4</td>
  </tr>
  <tr class="bg2">
   <td>Pongo abelii</td>
   <td class="right">5.8</td>
  </tr>
  <tr class="bg1">
   <td>Procavia capensis</td>
   <td class="right">5.7</td>
  </tr>
  <tr class="bg2">
   <td>Prolemur simus</td>
   <td class="right">11.0</td>
  </tr>
  <tr class="bg1">
   <td>Propithecus coquereli</td>
   <td class="right">12.4</td>
  </tr>
  <tr class="bg2">
   <td>Pseudonaja textilis</td>
   <td class="right">2.8</td>
  </tr>
  <tr class="bg1">
   <td>Pteropus vampyrus</td>
   <td class="right">5.9</td>
  </tr>
  <tr class="bg2">
   <td>Pundamilia nyererei</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Pygocentrus nattereri</td>
   <td class="right">3.9</td>
  </tr>
  <tr class="bg2">
   <td>Rattus norvegicus</td>
   <td class="right">36.6</td>
  </tr>
  <tr class="bg1">
   <td>Rhinolophus ferrumequinum</td>
   <td class="right">3.6</td>
  </tr>
  <tr class="bg2">
   <td>Rhinopithecus bieti</td>
   <td class="right">19.9</td>
  </tr>
  <tr class="bg1">
   <td>Rhinopithecus roxellana</td>
   <td class="right">19.6</td>
  </tr>
  <tr class="bg2">
   <td>Saccharomyces cerevisiae</td>
   <td class="right">0.6</td>
  </tr>
  <tr class="bg1">
   <td>Saimiri boliviensis</td>
   <td class="right">16.0</td>
  </tr>
  <tr class="bg2">
   <td>Salarias fasciatus</td>
   <td class="right">1.9</td>
  </tr>
  <tr class="bg1">
   <td>Salmo salar</td>
   <td class="right">51.9</td>
  </tr>
  <tr class="bg2">
   <td>Salmo trutta</td>
   <td class="right">7.8</td>
  </tr>
  <tr class="bg1">
   <td>Salvator merianae</td>
   <td class="right">3.5</td>
  </tr>
  <tr class="bg2">
   <td>Sander lucioperca</td>
   <td class="right">2.4</td>
  </tr>
  <tr class="bg1">
   <td>Sarcophilus harrisii</td>
   <td class="right">8.5</td>
  </tr>
  <tr class="bg2">
   <td>Sciurus vulgaris</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg1">
   <td>Scleropages formosus</td>
   <td class="right">3.0</td>
  </tr>
  <tr class="bg2">
   <td>Scophthalmus maximus</td>
   <td class="right">5.7</td>
  </tr>
  <tr class="bg1">
   <td>Serinus canaria</td>
   <td class="right">2.4</td>
  </tr>
  <tr class="bg2">
   <td>Seriola dumerili</td>
   <td class="right">3.7</td>
  </tr>
  <tr class="bg1">
   <td>Seriola lalandi</td>
   <td class="right">3.9</td>
  </tr>
  <tr class="bg2">
   <td>Sinocyclocheilus anshuiensis</td>
   <td class="right">4.6</td>
  </tr>
  <tr class="bg1">
   <td>Sinocyclocheilus grahami</td>
   <td class="right">5.0</td>
  </tr>
  <tr class="bg2">
   <td>Sinocyclocheilus rhinocerous</td>
   <td class="right">4.3</td>
  </tr>
  <tr class="bg1">
   <td>Sorex araneus</td>
   <td class="right">5.6</td>
  </tr>
  <tr class="bg2">
   <td>Sparus aurata</td>
   <td class="right">4.2</td>
  </tr>
  <tr class="bg1">
   <td>Spermophilus dauricus</td>
   <td class="right">4.7</td>
  </tr>
  <tr class="bg2">
   <td>Sphaeramia orbicularis</td>
   <td class="right">2.7</td>
  </tr>
  <tr class="bg1">
   <td>Sphenodon punctatus</td>
   <td class="right">8.1</td>
  </tr>
  <tr class="bg2">
   <td>Stachyris ruficeps</td>
   <td class="right">1.6</td>
  </tr>
  <tr class="bg1">
   <td>Stegastes partitus</td>
   <td class="right">3.8</td>
  </tr>
  <tr class="bg2">
   <td>Strigops habroptila</td>
   <td class="right">2.3</td>
  </tr>
  <tr class="bg1">
   <td>Strix occidentalis</td>
   <td class="right">1.8</td>
  </tr>
  <tr class="bg2">
   <td>Struthio camelus</td>
   <td class="right">2.7</td>
  </tr>
  <tr class="bg1">
   <td>Suricata suricatta</td>
   <td class="right">5.2</td>
  </tr>
  <tr class="bg2">
   <td>Sus scrofa</td>
   <td class="right">194.2</td>
  </tr>
  <tr class="bg1">
   <td>Taeniopygia guttata</td>
   <td class="right">4.1</td>
  </tr>
  <tr class="bg2">
   <td>Takifugu rubripes</td>
   <td class="right">3.7</td>
  </tr>
  <tr class="bg1">
   <td>Terrapene carolina</td>
   <td class="right">3.6</td>
  </tr>
  <tr class="bg2">
   <td>Tetraodon nigroviridis</td>
   <td class="right">4.5</td>
  </tr>
  <tr class="bg1">
   <td>Theropithecus gelada</td>
   <td class="right">16.4</td>
  </tr>
  <tr class="bg2">
   <td>Tupaia belangeri</td>
   <td class="right">6.6</td>
  </tr>
  <tr class="bg1">
   <td>Tursiops truncatus</td>
   <td class="right">6.4</td>
  </tr>
  <tr class="bg2">
   <td>Urocitellus parryii</td>
   <td class="right">4.1</td>
  </tr>
  <tr class="bg1">
   <td>Ursus americanus</td>
   <td class="right">5.3</td>
  </tr>
  <tr class="bg2">
   <td>Ursus maritimus</td>
   <td class="right">5.1</td>
  </tr>
  <tr class="bg1">
   <td>Ursus thibetanus</td>
   <td class="right">4.2</td>
  </tr>
  <tr class="bg2">
   <td>Varanus komodoensis</td>
   <td class="right">2.4</td>
  </tr>
  <tr class="bg1">
   <td>Vicugna pacos</td>
   <td class="right">4.6</td>
  </tr>
  <tr class="bg2">
   <td>Vombatus ursinus</td>
   <td class="right">7.1</td>
  </tr>
  <tr class="bg1">
   <td>Vulpes vulpes</td>
   <td class="right">7.7</td>
  </tr>
  <tr class="bg2">
   <td>Xenopus tropicalis</td>
   <td class="right">6.7</td>
  </tr>
  <tr class="bg1">
   <td>Xiphophorus couchianus</td>
   <td class="right">2.9</td>
  </tr>
  <tr class="bg2">
   <td>Xiphophorus maculatus</td>
   <td class="right">4.4</td>
  </tr>
  <tr class="bg1">
   <td>Zalophus californianus</td>
   <td class="right">5.1</td>
  </tr>
  <tr class="bg2">
   <td>Zonotrichia albicollis</td>
   <td class="right">2.2</td>
  </tr>
  <tr class="bg1">
   <td>Zosterops lateralis</td>
   <td class="right">1.5</td>
  </tr>
  <tr>
   <th>Sub-total</th>
   <th class="right">5322.4</th>
  </tr>

  <tr>
   <th>Multi-species</th>
   <th></th>
  </tr>
  <tr class="bg2">
   <td>Ancestral</td>
   <td class="right">135.7</td>
  </tr>
  <tr class="bg1">
   <td>Autocomplete</td>
   <td class="right">0.6</td>
  </tr>
  <tr class="bg2">
   <td>Compara</td>
   <td class="right">746.7</td>
  </tr>
  <tr class="bg1">
   <td>Mart</td>
   <td class="right">2329.9</td>
  </tr>
  <tr class="bg2">
   <td>Metadata</td>
   <td class="right">12.4</td>
  </tr>
  <tr class="bg1">
   <td>Ontology</td>
   <td class="right">1.6</td>
  </tr>
  <tr class="bg2">
   <td>Production</td>
   <td class="right">0.0</td>
  </tr>
  <tr class="bg1">
   <td>Stable</td>
   <td class="right">61.0</td>
  </tr>
  <tr class="bg2">
   <td>Website</td>
   <td class="right">0.0</td>
  </tr>
  <tr>
   <th>Total</th>
   <th class="right">8610.3</th>
  </tr>
 </tbody>
</table>
