// Generated by CoffeeScript 1.5.0

/* Do not edit this .js, edit the .coffee file and recompile
*/


(function() {

  (function($) {
    var center, overflowed;
    $.fn.centered = function(options) {
      var opts;
      if ($.type(options) === 'string') {
        if (options === 'redo') {
          return this.each(function() {
            return $(this).trigger('redo');
          });
        }
      } else {
        opts = $.extend({}, $.fn.centered.defaults, options);
        return this.each(function() {
          center($(this), opts);
          return $(this).on('redo', function(e) {
            return center($(this), opts);
          });
        });
      }
    };
    center = function(el, opts) {
      var fs, inner, size, space, _i, _ref, _ref1, _ref2;
      if (el.find('.centeredinner').length) {
        el.html(el.find('.centeredinner').html());
      }
      inner = $("<div/>").html(el.html()).css('word-wrap', 'break-word');
      el.empty().append(inner).css('line-height', 'normal');
      inner.addClass('centeredinner');
      size = null;
      for (fs = _i = _ref = opts.min, _ref1 = opts.max, _ref2 = opts.inc; _ref2 > 0 ? _i <= _ref1 : _i >= _ref1; fs = _i += _ref2) {
        inner.css('font-size', fs + 'px');
        if (overflowed(inner)) {
          break;
        }
        size = fs;
      }
      if (size) {
        inner.css('font-size', size + 'px');
      }
      space = el.height() - inner.outerHeight();
      if (space % 2) {
        space -= 1;
      }
      space /= 2;
      return inner.css({
        'margin-top': space,
        'margin-bottom': space,
        'text-align': 'center'
      });
    };
    overflowed = function(el) {
      if (el.height() > el.parent().height() || el.width() > el.parent().width()) {
        return true;
      } else {
        return false;
      }
    };
    return $.fn.centered.defaults = {
      min: 5,
      max: 100,
      inc: 5
    };
  })(jQuery);

}).call(this);
