// Generated by CoffeeScript 2.3.1
(function() {
  // Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
  // Copyright [2016-2018] EMBL-European Bioinformatics Institute

  // Licensed under the Apache License, Version 2.0 (the "License");
  // you may not use this file except in compliance with the License.
  // You may obtain a copy of the License at

  //     http://www.apache.org/licenses/LICENSE-2.0

  // Unless required by applicable law or agreed to in writing, software
  // distributed under the License is distributed on an "AS IS" BASIS,
  // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  // See the License for the specific language governing permissions and
  // limitations under the License.

  // Comment on next line is for js output only. Please ignore here.
  /* Do not edit this .js, edit the .coffee file and recompile */
  (function($) {
    var get, setup;
    $.solr_config = function(options, ...params) {
      var opts;
      if ($.type(options) === 'string') {
        return get(options, params);
      } else {
        opts = $.extend({}, $.solr_config.defaults, options);
        return setup(opts);
      }
    };
    setup = function(opts) {
      if ($('html').data('config')) {
        return new $.Deferred().resolve();
      }
      return $.ajax({
        url: opts.url,
        dataType: 'json'
      }).done(function(data) {
        return $('html').data('config', data);
      });
    };
    get = function(path, params) {
      var argidx, data, e, i, j, k, len, len1, next, ref, val;
      data = $('html').data('config');
      argidx = 0;
      ref = path.split('.');
      for (i = 0, len = ref.length; i < len; i++) {
        k = ref[i];
        if (data == null) {
          continue;
        }
        if (k === '%') {
          data = data[params[argidx]];
          argidx += 1;
        } else if (k.charAt(k.length - 1) === '=') {
          k = k.substring(0, k.length - 1);
          val = params[argidx];
          argidx += 1;
          next = null;
          for (j = 0, len1 = data.length; j < len1; j++) {
            e = data[j];
            if (e[k] === val) {
              next = e;
            }
          }
          data = next;
        } else {
          data = data[k];
        }
      }
      return data;
    };
    return $.solr_config.defaults = {};
  })(jQuery);

}).call(this);
