// Generated by CoffeeScript 1.5.0

/* Do not edit this .js, edit the .coffee file and recompile
*/


(function() {
  var __slice = [].slice;

  (function($) {
    var get, setup;
    $.solr_config = function() {
      var options, opts, params;
      options = arguments[0], params = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if ($.type(options) === 'string') {
        return get(options, params);
      } else {
        opts = $.extend({}, $.solr_config.defaults, options);
        return setup(opts);
      }
    };
    setup = function(opts) {
      if ($('html').data('config')) {
        return new $.Deferred().resolve();
      }
      return $.ajax({
        url: opts.url,
        dataType: 'json'
      }).done(function(data) {
        return $('html').data('config', data);
      });
    };
    get = function(path, params) {
      var argidx, data, e, k, next, val, _i, _j, _len, _len1, _ref;
      data = $('html').data('config');
      argidx = 0;
      _ref = path.split('.');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        k = _ref[_i];
        if (data == null) {
          continue;
        }
        if (k === '%') {
          data = data[params[argidx]];
          argidx += 1;
        } else if (k.charAt(k.length - 1) === '=') {
          k = k.substring(0, k.length - 1);
          val = params[argidx];
          argidx += 1;
          next = null;
          for (_j = 0, _len1 = data.length; _j < _len1; _j++) {
            e = data[_j];
            if (e[k] === val) {
              next = e;
            }
          }
          data = next;
        } else {
          data = data[k];
        }
      }
      return data;
    };
    return $.solr_config.defaults = {};
  })(jQuery);

}).call(this);
