// Generated by CoffeeScript 1.5.0
(function() {

  window.rate_limiter = function(nochange_ms, lastreq_ms) {
    var last_request, pending, timer;
    timer = null;
    last_request = null;
    pending = null;
    return function(data) {
      var d, now;
      d = $.Deferred();
      if (pending) {
        pending.reject();
        clearTimeout(timer);
        pending = null;
      }
      now = new Date().getTime();
      if ((!last_request) || now - last_request > lastreq_ms) {
        last_request = now;
        d.resolve(data);
      } else {
        pending = d;
        last_request = now;
        timer = setTimeout((function() {
          return d.resolve(data);
        }), nochange_ms);
      }
      return d;
    };
  };

  window.ensure_currency = function() {
    var idx;
    idx = 0;
    return function() {
      idx += 1;
      return (function(cidx) {
        return (function(data) {
          if (cidx === idx) {
            return data;
          } else {
            return $.Deferred().reject();
          }
        });
      })(idx);
    };
  };

}).call(this);
