// Generated by CoffeeScript 1.12.6
(function() {
  var in_endless_chunks;

  window.rate_limiter = function(nochange_ms, lastreq_ms) {
    var last_request, pending, timer;
    timer = null;
    last_request = null;
    pending = null;
    return function(data) {
      var d, now;
      d = $.Deferred();
      if (pending) {
        pending.reject();
        clearTimeout(timer);
        pending = null;
      }
      now = new Date().getTime();
      if ((!last_request) || now - last_request > lastreq_ms) {
        last_request = now;
        d.resolve(data);
      } else {
        pending = d;
        last_request = now;
        timer = setTimeout((function() {
          return d.resolve(data);
        }), nochange_ms);
      }
      return d;
    };
  };

  window.then_loop = function(fn) {
    var step;
    step = function(v) {
      var d;
      d = fn(v);
      if (d && $.isFunction(d.promise)) {
        return d.then(step);
      } else {
        return d;
      }
    };
    return step;
  };

  in_endless_chunks = function(chunksize, fn) {
    var chunk_loop;
    chunk_loop = then_loop((function(_this) {
      return function(arg) {
        var got, halt;
        got = arg[0], halt = arg[1];
        if (halt) {
          return got;
        }
        return fn(got, chunksize).then(function(len) {
          if (len === -1) {
            return [got, 1];
          } else {
            return [got + len, 0];
          }
        });
      };
    })(this));
    return $.Deferred().resolve([0, 0]).then(chunk_loop);
  };

  window.in_chunks = function(total, maxchunksize, fn) {
    var chunk_loop;
    if (total === -1) {
      return in_endless_chunks(maxchunksize, fn);
    }
    chunk_loop = then_loop((function(_this) {
      return function(got) {
        var chunksize;
        if (total - got <= 0) {
          return got;
        }
        chunksize = total - got;
        if (chunksize > maxchunksize) {
          chunksize = maxchunksize;
        }
        return fn(got, chunksize).then(function(len) {
          return got + len;
        });
      };
    })(this));
    return $.Deferred().resolve(0).then(chunk_loop);
  };

  window.solr_current_species = function() {
    var latin, parts, path, species, url;
    url = window.location.href;
    parts = url.split('/');
    path = parts[3].toLowerCase();
    latin = $.solr_config('spnames.%', path);
    if (!latin) {
      latin = path;
    }
    species = latin.toLowerCase();
    if (!$.solr_config('revspnames.%', species)) {
      return null;
    }
    return species;
  };

}).call(this);
