// Generated by CoffeeScript 1.5.0
(function() {

  if (typeof String.prototype.trim !== 'function') {
    String.prototype.trim = function() {
      return this.replace(/^\s+|\s+$/g, '');
    };
  }

  if (typeof Array.prototype.indexOf !== 'function') {
    Array.prototype.indexOf = function(obj, start) {
      var i, _i, _ref, _ref1;
      for (i = _i = _ref = start != null ? start : 0, _ref1 = this.length; _ref <= _ref1 ? _i < _ref1 : _i > _ref1; i = _ref <= _ref1 ? ++_i : --_i) {
        if (this[i] === obj) {
          return i;
        }
      }
      return -1;
    };
  }

}).call(this);
