<h4>G.gal-H.sap synteny</h4>
Gallus gallus<br />
Homo sapiens<br />
<h4>H.sap-B.tau synteny</h4>
Homo sapiens<br />
Bos taurus<br />
<h4>H.sap-C.fam synteny</h4>
Homo sapiens<br />
Canis familiaris<br />
<h4>H.sap-E.cab synteny</h4>
Homo sapiens<br />
Equus caballus<br />
<h4>H.sap-M.dom synteny</h4>
Homo sapiens<br />
Monodelphis domestica<br />
<h4>H.sap-M.mul synteny</h4>
Homo sapiens<br />
Macaca mulatta<br />
<h4>H.sap-M.mus synteny</h4>
Homo sapiens<br />
Mus musculus<br />
<h4>H.sap-P.pyg synteny</h4>
Homo sapiens<br />
Pongo pygmaeus<br />
<h4>H.sap-P.tro synteny</h4>
Pan troglodytes<br />
Homo sapiens<br />
<h4>M.mus-C.fam synteny</h4>
Canis familiaris<br />
Mus musculus<br />
<h4>M.mus-R.nor synteny</h4>
Mus musculus<br />
Rattus norvegicus<br />
<h4>R.nor-H.sap synteny</h4>
Homo sapiens<br />
Rattus norvegicus<br />
