#!/usr/local/bin/perl

=head1 NAME

rsync_code_to_shared

=head1 DESCRIPTION

Rsync folders of the required code to a shared location to make it
accessible to the LSF or other machines that allow job queueing.

=head1 LICENSE

Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Copyright [2016-2024] EMBL-European Bioinformatics Institute

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=head1 CONTACT

Post questions to the EnsEMBL webteam list helpdesk@ensembl.org

=cut

use strict;
use warnings;

if (grep(m/^synchive/, @ARGV) && (my @lsf_hosts = @{ $SiteDefs::ENSEMBL_HIVE_HOSTS || [] })) {

  my $source  = $SiteDefs::ENSEMBL_SERVERROOT;
  my $dest    = $SiteDefs::ENSEMBL_HIVE_HOSTS_CODE_LOCATION;
  my $args    = grep($_ eq 'synchiveverbose', @ARGV) ? '-aWv' : '-aWvq';

  for (@lsf_hosts) {
    print "Copying code from $source to $_:$dest\n";
    system(sprintf 'rsync %s --exclude=".git*"  --exclude="sitemaps" --exclude="conf/book" --exclude="opensearch/" --exclude="beekeeper.*log" --delete %s %s:%s', $args, join(' ', map("$source/$_", @SiteDefs::ENSEMBL_TOOLS_LIB_DIRS)), $_, $dest);
  }
}

1;
