
<table class="ss autocenter" style="width:50%;margin:0 25%" cellspacing="0">
 <tbody>
  <tr class="ss_header">
   <th class="bottom-border left-border">Species</th>
   <th class="bottom-border right-border">Data size (Gb)</th>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Aedes aegypti                   </td>
   <td class="right-border" style="text-align:right">5.0        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Anopheles gambiae               </td>
   <td class="right-border" style="text-align:right">2.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Bos taurus                      </td>
   <td class="right-border" style="text-align:right">9.8        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Caenorhabditis elegans          </td>
   <td class="right-border" style="text-align:right">2.8        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Canis familiaris                </td>
   <td class="right-border" style="text-align:right">9.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Cavia porcellus                 </td>
   <td class="right-border" style="text-align:right">3.6        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Ciona intestinalis              </td>
   <td class="right-border" style="text-align:right">2.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Ciona savignyi                  </td>
   <td class="right-border" style="text-align:right">2.7        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Danio rerio                     </td>
   <td class="right-border" style="text-align:right">7.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Dasypus novemcinctus            </td>
   <td class="right-border" style="text-align:right">5.2        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Drosophila melanogaster         </td>
   <td class="right-border" style="text-align:right">1.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Echinops telfairi               </td>
   <td class="right-border" style="text-align:right">5.8        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Equus caballus                  </td>
   <td class="right-border" style="text-align:right">7.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Erinaceus europaeus             </td>
   <td class="right-border" style="text-align:right">7.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Felis catus                     </td>
   <td class="right-border" style="text-align:right">6.0        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Gallus gallus                   </td>
   <td class="right-border" style="text-align:right">6.1        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Gasterosteus aculeatus          </td>
   <td class="right-border" style="text-align:right">4.7        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Homo sapiens                    </td>
   <td class="right-border" style="text-align:right">42.6       </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Loxodonta africana              </td>
   <td class="right-border" style="text-align:right">5.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Macaca mulatta                  </td>
   <td class="right-border" style="text-align:right">6.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Microcebus murinus              </td>
   <td class="right-border" style="text-align:right">5.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Monodelphis domestica           </td>
   <td class="right-border" style="text-align:right">9.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Mus musculus                    </td>
   <td class="right-border" style="text-align:right">28.1       </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Myotis lucifugus                </td>
   <td class="right-border" style="text-align:right">5.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Ochotona princeps               </td>
   <td class="right-border" style="text-align:right">8.8        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Ornithorhynchus anatinus        </td>
   <td class="right-border" style="text-align:right">7.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Oryctolagus cuniculus           </td>
   <td class="right-border" style="text-align:right">6.0        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Oryzias latipes                 </td>
   <td class="right-border" style="text-align:right">4.2        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Otolemur garnettii              </td>
   <td class="right-border" style="text-align:right">5.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Pan troglodytes                 </td>
   <td class="right-border" style="text-align:right">9.8        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Pongo pygmaeus                  </td>
   <td class="right-border" style="text-align:right">8.1        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Rattus norvegicus               </td>
   <td class="right-border" style="text-align:right">11.2       </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Saccharomyces cerevisiae        </td>
   <td class="right-border" style="text-align:right">0.2        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Sorex araneus                   </td>
   <td class="right-border" style="text-align:right">5.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Spermophilus tridecemlineatus   </td>
   <td class="right-border" style="text-align:right">4.9        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Takifugu rubripes               </td>
   <td class="right-border" style="text-align:right">4.3        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Tetraodon nigroviridis          </td>
   <td class="right-border" style="text-align:right">4.0        </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Tupaia belangeri                </td>
   <td class="right-border" style="text-align:right">6.4        </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Xenopus tropicalis              </td>
   <td class="right-border" style="text-align:right">6.3        </td>
  </tr>
  <tr>
   <th class="left-border">Sub-total</th>
   <th class="right-border" style="text-align:right">286.0      </th>
  </tr>

  <tr>
   <th class="left-border">Multi-species</th>
   <th class="right-border">&nbsp;</th>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Ancestral                       </td>
   <td class="right-border" style="text-align:right">50.8       </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Compara                         </td>
   <td class="right-border" style="text-align:right">134.8      </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Go                              </td>
   <td class="right-border" style="text-align:right">12.2       </td>
  </tr>
  <tr style="vertical-align:top" class="bg1">
   <td class="left-border">Mart                            </td>
   <td class="right-border" style="text-align:right">141.0      </td>
  </tr>
  <tr style="vertical-align:top" class="bg2">
   <td class="left-border">Website                         </td>
   <td class="right-border" style="text-align:right">0.0        </td>
  </tr>
  <tr>
   <th class="left-border">Total</th>
   <th class="right-border" style="text-align:right">624.8      </th>
  </tr>
 </tbody>
</table>
