
<table class="spreadsheet" cellpadding="4">

<tr>
<th>Species</th>
<th>DNA</th>
<th>cDNA</th>
<th>Peptides</th>
<th>EMBL</th>
<th>GenBank</th>
<th>MySQL</th>
</tr>


<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/aedes_aegypti_42_1a/"><i>Aedes aegypti</i></a> (yellow fever mosquito)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/aedes_aegypti_42_1a/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/aedes_aegypti_42_1a/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/aedes_aegypti_42_1a/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/aedes_aegypti_42_1a/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/aedes_aegypti_42_1a/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/aedes_aegypti_42_1a/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/anopheles_gambiae_42_3e/"><i>Anopheles gambiae</i></a> (African malaria mosquito)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/anopheles_gambiae_42_3e/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/anopheles_gambiae_42_3e/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/anopheles_gambiae_42_3e/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/anopheles_gambiae_42_3e/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/anopheles_gambiae_42_3e/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/anopheles_gambiae_42_3e/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/bos_taurus_42_2e/"><i>Bos taurus</i></a> (cattle)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/bos_taurus_42_2e/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/bos_taurus_42_2e/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/bos_taurus_42_2e/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/bos_taurus_42_2e/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/bos_taurus_42_2e/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/bos_taurus_42_2e/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/caenorhabditis_elegans_42_160/"><i>Caenorhabditis elegans</i></a> (nematode)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/caenorhabditis_elegans_42_160/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/caenorhabditis_elegans_42_160/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/caenorhabditis_elegans_42_160/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/caenorhabditis_elegans_42_160/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/caenorhabditis_elegans_42_160/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/caenorhabditis_elegans_42_160/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/canis_familiaris_42_2/"><i>Canis familiaris</i></a> (dog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/canis_familiaris_42_2/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/canis_familiaris_42_2/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/canis_familiaris_42_2/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/canis_familiaris_42_2/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/canis_familiaris_42_2/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/canis_familiaris_42_2/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_intestinalis_42_2d/"><i>Ciona intestinalis</i></a> (Sea squirt Ciona intestinalis)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_intestinalis_42_2d/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_intestinalis_42_2d/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_intestinalis_42_2d/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_intestinalis_42_2d/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_intestinalis_42_2d/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_intestinalis_42_2d/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_savignyi_42_2c/"><i>Ciona savignyi</i></a> (Sea squirt Ciona savignyi)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_savignyi_42_2c/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_savignyi_42_2c/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_savignyi_42_2c/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_savignyi_42_2c/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_savignyi_42_2c/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ciona_savignyi_42_2c/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/danio_rerio_42_6c/"><i>Danio rerio</i></a> (zebrafish)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/danio_rerio_42_6c/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/danio_rerio_42_6c/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/danio_rerio_42_6c/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/danio_rerio_42_6c/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/danio_rerio_42_6c/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/danio_rerio_42_6c/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/dasypus_novemcinctus_42_1b/"><i>Dasypus novemcinctus</i></a> (nine-banded armadillo)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/dasypus_novemcinctus_42_1b/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/dasypus_novemcinctus_42_1b/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/dasypus_novemcinctus_42_1b/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/dasypus_novemcinctus_42_1b/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/dasypus_novemcinctus_42_1b/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/dasypus_novemcinctus_42_1b/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/drosophila_melanogaster_42_43/"><i>Drosophila melanogaster</i></a> (fruit fly)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/drosophila_melanogaster_42_43/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/drosophila_melanogaster_42_43/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/drosophila_melanogaster_42_43/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/drosophila_melanogaster_42_43/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/drosophila_melanogaster_42_43/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/drosophila_melanogaster_42_43/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/echinops_telfairi_42_1b/"><i>Echinops telfairi</i></a> (small Madagascar hedgehog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/echinops_telfairi_42_1b/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/echinops_telfairi_42_1b/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/echinops_telfairi_42_1b/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/echinops_telfairi_42_1b/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/echinops_telfairi_42_1b/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/echinops_telfairi_42_1b/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gallus_gallus_42_2/"><i>Gallus gallus</i></a> (chicken)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gallus_gallus_42_2/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gallus_gallus_42_2/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gallus_gallus_42_2/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gallus_gallus_42_2/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gallus_gallus_42_2/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gallus_gallus_42_2/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gasterosteus_aculeatus_42_1b/"><i>Gasterosteus aculeatus</i></a> (three spined stickleback)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gasterosteus_aculeatus_42_1b/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gasterosteus_aculeatus_42_1b/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gasterosteus_aculeatus_42_1b/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gasterosteus_aculeatus_42_1b/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gasterosteus_aculeatus_42_1b/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/gasterosteus_aculeatus_42_1b/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/homo_sapiens_42_36d/"><i>Homo sapiens</i></a> (human)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/homo_sapiens_42_36d/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/homo_sapiens_42_36d/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/homo_sapiens_42_36d/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/homo_sapiens_42_36d/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/homo_sapiens_42_36d/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/homo_sapiens_42_36d/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/loxodonta_africana_42_1b/"><i>Loxodonta africana</i></a> (African savanna elephant)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/loxodonta_africana_42_1b/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/loxodonta_africana_42_1b/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/loxodonta_africana_42_1b/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/loxodonta_africana_42_1b/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/loxodonta_africana_42_1b/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/loxodonta_africana_42_1b/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/macaca_mulatta_42_10b/"><i>Macaca mulatta</i></a> (rhesus monkey)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/macaca_mulatta_42_10b/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/macaca_mulatta_42_10b/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/macaca_mulatta_42_10b/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/macaca_mulatta_42_10b/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/macaca_mulatta_42_10b/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/macaca_mulatta_42_10b/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/monodelphis_domestica_42_3b/"><i>Monodelphis domestica</i></a> (gray short-tailed opossum)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/monodelphis_domestica_42_3b/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/monodelphis_domestica_42_3b/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/monodelphis_domestica_42_3b/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/monodelphis_domestica_42_3b/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/monodelphis_domestica_42_3b/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/monodelphis_domestica_42_3b/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/mus_musculus_42_36c/"><i>Mus musculus</i></a> (house mouse)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/mus_musculus_42_36c/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/mus_musculus_42_36c/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/mus_musculus_42_36c/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/mus_musculus_42_36c/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/mus_musculus_42_36c/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/mus_musculus_42_36c/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ornithorhynchus_anatinus_42_1/"><i>Ornithorhynchus anatinus</i></a> (platypus)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ornithorhynchus_anatinus_42_1/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ornithorhynchus_anatinus_42_1/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ornithorhynchus_anatinus_42_1/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ornithorhynchus_anatinus_42_1/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ornithorhynchus_anatinus_42_1/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/ornithorhynchus_anatinus_42_1/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryctolagus_cuniculus_42_1b/"><i>Oryctolagus cuniculus</i></a> (rabbit)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryctolagus_cuniculus_42_1b/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryctolagus_cuniculus_42_1b/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryctolagus_cuniculus_42_1b/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryctolagus_cuniculus_42_1b/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryctolagus_cuniculus_42_1b/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryctolagus_cuniculus_42_1b/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryzias_latipes_42_1a/"><i>Oryzias latipes</i></a> (Japanese medaka)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryzias_latipes_42_1a/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryzias_latipes_42_1a/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryzias_latipes_42_1a/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryzias_latipes_42_1a/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryzias_latipes_42_1a/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/oryzias_latipes_42_1a/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/pan_troglodytes_42_21a/"><i>Pan troglodytes</i></a> (chimpanzee)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/pan_troglodytes_42_21a/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/pan_troglodytes_42_21a/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/pan_troglodytes_42_21a/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/pan_troglodytes_42_21a/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/pan_troglodytes_42_21a/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/pan_troglodytes_42_21a/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/rattus_norvegicus_42_34l/"><i>Rattus norvegicus</i></a> (Norway rat)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/rattus_norvegicus_42_34l/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/rattus_norvegicus_42_34l/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/rattus_norvegicus_42_34l/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/rattus_norvegicus_42_34l/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/rattus_norvegicus_42_34l/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/rattus_norvegicus_42_34l/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/saccharomyces_cerevisiae_42_1e/"><i>Saccharomyces cerevisiae</i></a> (baker's yeast)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/saccharomyces_cerevisiae_42_1e/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/saccharomyces_cerevisiae_42_1e/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/saccharomyces_cerevisiae_42_1e/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/saccharomyces_cerevisiae_42_1e/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/saccharomyces_cerevisiae_42_1e/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/saccharomyces_cerevisiae_42_1e/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/takifugu_rubripes_42_4d/"><i>Takifugu rubripes</i></a> (torafugu)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/takifugu_rubripes_42_4d/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/takifugu_rubripes_42_4d/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/takifugu_rubripes_42_4d/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/takifugu_rubripes_42_4d/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/takifugu_rubripes_42_4d/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/takifugu_rubripes_42_4d/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/tetraodon_nigroviridis_42_1h/"><i>Tetraodon nigroviridis</i></a> (Fresh water pufferfish)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/tetraodon_nigroviridis_42_1h/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/tetraodon_nigroviridis_42_1h/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/tetraodon_nigroviridis_42_1h/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/tetraodon_nigroviridis_42_1h/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/tetraodon_nigroviridis_42_1h/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/tetraodon_nigroviridis_42_1h/data/mysql/">FTP</a></td>
</tr>
	    
<tr>
<td>
<a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/xenopus_tropicalis_42_41c/"><i>Xenopus tropicalis</i></a> (western clawed frog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/xenopus_tropicalis_42_41c/data/fasta/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/xenopus_tropicalis_42_41c/data/fasta/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/xenopus_tropicalis_42_41c/data/fasta/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/xenopus_tropicalis_42_41c/data/flatfiles/embl/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/xenopus_tropicalis_42_41c/data/flatfiles/genbank/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/release-42/xenopus_tropicalis_42_41c/data/mysql/">FTP</a></td>
</tr>
	    </table>