
<table class="ss" cellpadding="4">

<tr>
<th>Species</th>
<th>DNA</th>
<th>cDNA</th>
<th>Peptides</th>
<th>EMBL</th>
<th>GenBank</th>
<th>MySQL</th>
<th>GTF</th>
<th>EMF</th>
</tr>


<tr>
<td><strong><i>Aedes aegypti</i></strong> (yellow fever mosquito)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti_48_1b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti_48_1b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/aedes_aegypti_48_1b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/aedes_aegypti_48_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/aedes_aegypti_48_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Anopheles gambiae</i></strong> (African malaria mosquito)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae_48_3j/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae_48_3j/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/anopheles_gambiae_48_3j/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/anopheles_gambiae_48_3j/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/anopheles_gambiae_48_3j/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Bos taurus</i></strong> (cattle)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus_48_3e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus_48_3e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus_48_3e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/bos_taurus_48_3e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/bos_taurus_48_3e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Caenorhabditis elegans</i></strong> (nematode)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans_48_180a/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans_48_180a/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans_48_180a/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/caenorhabditis_elegans_48_180a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/caenorhabditis_elegans_48_180a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Canis familiaris</i></strong> (dog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris_48_2f/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris_48_2f/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris_48_2f/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/canis_familiaris_48_2f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/canis_familiaris_48_2f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Cavia porcellus</i></strong> (domestic guinea pig)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus_48_1c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus_48_1c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus_48_1c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/cavia_porcellus_48_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/cavia_porcellus_48_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ciona intestinalis</i></strong> (Sea squirt Ciona intestinalis)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis_48_2h/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis_48_2h/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis_48_2h/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/ciona_intestinalis_48_2h/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/ciona_intestinalis_48_2h/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ciona savignyi</i></strong> (Sea squirt Ciona savignyi)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi_48_2f/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi_48_2f/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi_48_2f/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/ciona_savignyi_48_2f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/ciona_savignyi_48_2f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Danio rerio</i></strong> (zebrafish)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio_48_7b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio_48_7b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio_48_7b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/danio_rerio_48_7b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/danio_rerio_48_7b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Dasypus novemcinctus</i></strong> (nine-banded armadillo)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus_48_1e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus_48_1e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus_48_1e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/dasypus_novemcinctus_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/dasypus_novemcinctus_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Drosophila melanogaster</i></strong> (fruit fly)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster_48_43b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster_48_43b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster_48_43b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/drosophila_melanogaster_48_43b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/drosophila_melanogaster_48_43b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Echinops telfairi</i></strong> (small Madagascar hedgehog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi_48_1e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi_48_1e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi_48_1e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/echinops_telfairi_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/echinops_telfairi_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Erinaceus europaeus</i></strong> (western European hedgehog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus_48_1c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus_48_1c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus_48_1c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/erinaceus_europaeus_48_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/erinaceus_europaeus_48_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Felis catus</i></strong> (cat)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus_48_1c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus_48_1c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/felis_catus_48_1c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/felis_catus_48_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/felis_catus_48_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Gallus gallus</i></strong> (chicken)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus_48_2f/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus_48_2f/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus_48_2f/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/gallus_gallus_48_2f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/gallus_gallus_48_2f/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Gasterosteus aculeatus</i></strong> (three spined stickleback)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus_48_1e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus_48_1e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus_48_1e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/gasterosteus_aculeatus_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/gasterosteus_aculeatus_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Homo sapiens</i></strong> (human)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens_48_36j/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens_48_36j/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens_48_36j/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/homo_sapiens_48_36j/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/homo_sapiens_48_36j/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_emf/homo_sapiens_variation_48_36j/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Loxodonta africana</i></strong> (African savanna elephant)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana_48_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana_48_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana_48_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/loxodonta_africana_48_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/loxodonta_africana_48_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Macaca mulatta</i></strong> (rhesus monkey)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta_48_10g/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta_48_10g/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta_48_10g/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/macaca_mulatta_48_10g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/macaca_mulatta_48_10g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Microcebus murinus</i></strong> (grey mouse lemur)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/microcebus_murinus_48_1/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/microcebus_murinus_48_1/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/microcebus_murinus_48_1/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/microcebus_murinus_48_1/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/microcebus_murinus_48_1/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Monodelphis domestica</i></strong> (gray short-tailed opossum)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica_48_5c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica_48_5c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica_48_5c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/monodelphis_domestica_48_5c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/monodelphis_domestica_48_5c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Mus musculus</i></strong> (house mouse)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_48_37a/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_48_37a/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_48_37a/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/mus_musculus_48_37a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/mus_musculus_48_37a/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_emf/mus_musculus_variation_48_37a/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Myotis lucifugus</i></strong> (little brown bat)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus_48_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus_48_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus_48_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/myotis_lucifugus_48_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/myotis_lucifugus_48_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ochotona princeps</i></strong> (American pika)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ochotona_princeps_48_1/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ochotona_princeps_48_1/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ochotona_princeps_48_1/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/ochotona_princeps_48_1/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/ochotona_princeps_48_1/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Ornithorhynchus anatinus</i></strong> (platypus)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus_48_1e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus_48_1e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus_48_1e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/ornithorhynchus_anatinus_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/ornithorhynchus_anatinus_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Oryctolagus cuniculus</i></strong> (rabbit)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus_48_1e/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus_48_1e/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus_48_1e/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/oryctolagus_cuniculus_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/oryctolagus_cuniculus_48_1e/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Oryzias latipes</i></strong> (Japanese medaka)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes_48_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes_48_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes_48_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/oryzias_latipes_48_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/oryzias_latipes_48_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Otolemur garnettii</i></strong> (small-eared galago)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii_48_1b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii_48_1b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii_48_1b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/otolemur_garnettii_48_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/otolemur_garnettii_48_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Pan troglodytes</i></strong> (chimpanzee)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes_48_21g/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes_48_21g/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes_48_21g/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/pan_troglodytes_48_21g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/pan_troglodytes_48_21g/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Rattus norvegicus</i></strong> (Norway rat)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus_48_34r/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus_48_34r/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus_48_34r/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/rattus_norvegicus_48_34r/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/rattus_norvegicus_48_34r/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_emf/rattus_norvegicus_variation_48_34r/">FTP</a></td>
</tr>
	    
<tr>
<td><strong><i>Saccharomyces cerevisiae</i></strong> (baker's yeast)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae_48_1h/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae_48_1h/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae_48_1h/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/saccharomyces_cerevisiae_48_1h/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/saccharomyces_cerevisiae_48_1h/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Sorex araneus</i></strong> (European shrew)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus_48_1b/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus_48_1b/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus_48_1b/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/sorex_araneus_48_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/sorex_araneus_48_1b/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Spermophilus tridecemlineatus</i></strong> (thirteen-lined ground squirrel)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus_48_1d/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus_48_1d/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/spermophilus_tridecemlineatus_48_1d/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/spermophilus_tridecemlineatus_48_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/spermophilus_tridecemlineatus_48_1d/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Takifugu rubripes</i></strong> (torafugu)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes_48_4h/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes_48_4h/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes_48_4h/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/takifugu_rubripes_48_4h/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/takifugu_rubripes_48_4h/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Tetraodon nigroviridis</i></strong> (Fresh water pufferfish)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis_48_1j/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis_48_1j/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis_48_1j/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/tetraodon_nigroviridis_48_1j/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/tetraodon_nigroviridis_48_1j/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Tupaia belangeri</i></strong> (northern tree shrew)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri_48_1c/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri_48_1c/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri_48_1c/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/tupaia_belangeri_48_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/tupaia_belangeri_48_1c/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong><i>Xenopus tropicalis</i></strong> (western clawed frog)</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis_48_41h/dna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis_48_41h/cdna/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis_48_41h/pep/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_embl/xenopus_tropicalis_48_41h/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_genbank/xenopus_tropicalis_48_41h/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_gtf/">FTP</a></td>
<td>-</td>
</tr>
	    
<tr>
<td><strong>Multi-species</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td>-</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_emf/">FTP</a></td>
</tr>
<tr>
<td><strong>Ensembl Mart</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td><a target="ftp" href="ftp://ftp.ensembl.org/pub/current_mysql/">FTP</a></td>
<td>-</td>
<td>-</td>
</tr>
      </table>